// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.rootSettings;

import java.awt.*;
import java.awt.event.*;
import java.util.logging.Logger;
import javax.swing.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.delegate.*;
import com.viaoa.docbuilder.model.search.*;
import com.viaoa.docbuilder.resource.Resource;
import com.viaoa.docbuilder.view.oa.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.border.ShadowBorder;

public class RootSettingsPanelBase {
    private static Logger LOG = Logger.getLogger(RootSettingsPanelBase.class.getName());
    
    private JRadioButtonMenuItem mi; 
    private JToggleButton toggleButton;
    
    private JSplitPane splitPane;
    private OAOutlookBar outlookBar;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    
    public static final String CARD_SettingsBar = "SettingsBar";
    
    protected SettingsBar barSettings;
    
    public RootSettingsPanelBase() {
        cardLayout = new CardLayout();
        cardPanel = new JPanel(cardLayout);
        
        splitPane = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, getOutlookBar(), cardPanel);
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(.05d);
        
        ImageIcon icon;
        icon = Resource.getJarIcon("rootSettingsBar.png");
        outlookBar.addBar(CARD_SettingsBar, "Settings", icon, new JScrollPane(getSettingsBar().getTree()));
        cardPanel.add(getSettingsBar().getPanel(), CARD_SettingsBar);
    }
    
    public SettingsBar getSettingsBar() {
        if (barSettings != null) return barSettings;
        barSettings = new SettingsBar();
        new HubChangeListener(ModelDelegate.getLocalAppUserHub(), AppUserPP.admin(), true) {
            @Override
            protected void onChange() {
                outlookBar.setVisible(CARD_SettingsBar, getValue());
            }
        };
        return barSettings;
    }
    
    public OAOutlookBar getOutlookBar() {
        if (outlookBar != null) return outlookBar;
        outlookBar = new OAOutlookBar() {
            @Override
            protected void onBarSelected(String barName) {
                cardLayout.show(cardPanel, barName);
            }
        };
        int w = OAJfcUtil.getCharWidth(23);
        outlookBar.setPreferredSize(new Dimension(w, 50));
        outlookBar.setBorder(new ShadowBorder());
        Dimension d = outlookBar.getMinimumSize();
        w = OAJfcUtil.getCharWidth(1);
        d.width = w;
        outlookBar.setMinimumSize(d);
        outlookBar.setMinimumSize(new Dimension(10,10));
        return outlookBar;
    }
    
    public JToggleButton getToggleButton() {
        if (toggleButton != null) return toggleButton;
        toggleButton = new JToggleButton("Settings");
        ImageIcon ii = Resource.getJarIcon("rootSettingsButton.png");
        toggleButton.setIcon(ii);
        toggleButton.setVerticalTextPosition(SwingConstants.BOTTOM);
        toggleButton.setHorizontalTextPosition(SwingConstants.CENTER);
        toggleButton.setMnemonic('S');
        toggleButton.setToolTipText("show the Settings panel");
        return toggleButton;
    }
    
    public JRadioButtonMenuItem getMenuItem() {
        if (mi != null) return mi;
        mi = new JRadioButtonMenuItem();
        mi.setMnemonic(KeyEvent.VK_S);
        mi.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_S, InputEvent.ALT_MASK, false));
        mi.setText("Settings panel");
        mi.setToolTipText("show the RootSettings panel");
        return mi;
    }
    
    public JSplitPane getSplitPane() {
        return splitPane;
    }
    public JComponent getMainComponent() {
        return splitPane;
    }
}

