// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.rootSettings;

import java.util.logging.Logger;

public class RootSettingsPanel extends RootSettingsPanelBase {
    private static Logger LOG = Logger.getLogger(RootSettingsPanel.class.getName());
}
