// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.rootSettings;

import java.util.logging.*;

public class SettingsBar extends SettingsBarBase {
    private static Logger LOG = Logger.getLogger(SettingsBarBase.class.getName());
}
