// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.rootProjects;

import java.util.logging.*;

public class ProjectsBar extends ProjectsBarBase {
    private static Logger LOG = Logger.getLogger(ProjectsBarBase.class.getName());
}
