// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.rootProjects;

import java.util.logging.Logger;

public class RootProjectsPanel extends RootProjectsPanelBase {
    private static Logger LOG = Logger.getLogger(RootProjectsPanel.class.getName());
}
