// Generated by OABuilder
package com.viaoa.docbuilder.remote;

import com.viaoa.remote.multiplexer.annotation.OARemoteInterface;
import com.viaoa.docbuilder.model.oa.api.*;

@OARemoteInterface
public interface APIInterface {
}
