// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class CodeSearchModel {
    private static Logger LOG = Logger.getLogger(CodeSearchModel.class.getName());
    
    protected Hub<Code> hub;  // search results
    protected Hub<Code> hubMultiSelect;
    protected Hub<Code> hubSearchFrom;  // hub (optional) to search from
    protected Hub<CodeSearch> hubCodeSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, Code> finder;
    
    // object used for search data
    protected CodeSearch codeSearch;
    
    public CodeSearchModel() {
    }
    
    public CodeSearchModel(Hub<Code> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<Code> getHub() {
        if (hub == null) {
            hub = new Hub<Code>(Code.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<Code> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<Code> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    CodeSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<Code> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(Code.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, Code> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, Code> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public CodeSearch getCodeSearch() {
        if (codeSearch != null) return codeSearch;
        codeSearch = new CodeSearch();
        return codeSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<CodeSearch> getCodeSearchHub() {
        if (hubCodeSearch == null) {
            hubCodeSearch = new Hub<CodeSearch>(CodeSearch.class);
            hubCodeSearch.add(getCodeSearch());
            hubCodeSearch.setPos(0);
        }
        return hubCodeSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses CodeSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<Code> sel = getCodeSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(Code code, Hub<Code> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<Code> hub) {
    }
}

