// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class LinkInfoSearchModel {
    private static Logger LOG = Logger.getLogger(LinkInfoSearchModel.class.getName());
    
    protected Hub<LinkInfo> hub;  // search results
    protected Hub<LinkInfo> hubMultiSelect;
    protected Hub<LinkInfo> hubSearchFrom;  // hub (optional) to search from
    protected Hub<LinkInfoSearch> hubLinkInfoSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, LinkInfo> finder;
    
    // object used for search data
    protected LinkInfoSearch linkInfoSearch;
    
    public LinkInfoSearchModel() {
    }
    
    public LinkInfoSearchModel(Hub<LinkInfo> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<LinkInfo> getHub() {
        if (hub == null) {
            hub = new Hub<LinkInfo>(LinkInfo.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<LinkInfo> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<LinkInfo> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    LinkInfoSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<LinkInfo> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(LinkInfo.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, LinkInfo> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, LinkInfo> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public LinkInfoSearch getLinkInfoSearch() {
        if (linkInfoSearch != null) return linkInfoSearch;
        linkInfoSearch = new LinkInfoSearch();
        return linkInfoSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<LinkInfoSearch> getLinkInfoSearchHub() {
        if (hubLinkInfoSearch == null) {
            hubLinkInfoSearch = new Hub<LinkInfoSearch>(LinkInfoSearch.class);
            hubLinkInfoSearch.add(getLinkInfoSearch());
            hubLinkInfoSearch.setPos(0);
        }
        return hubLinkInfoSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses LinkInfoSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<LinkInfo> sel = getLinkInfoSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(LinkInfo linkInfo, Hub<LinkInfo> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<LinkInfo> hub) {
    }
}

