// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class PageSearchModel {
    private static Logger LOG = Logger.getLogger(PageSearchModel.class.getName());
    
    protected Hub<Page> hub;  // search results
    protected Hub<Page> hubMultiSelect;
    protected Hub<Page> hubSearchFrom;  // hub (optional) to search from
    protected Hub<PageSearch> hubPageSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, Page> finder;
    
    // object used for search data
    protected PageSearch pageSearch;
    
    public PageSearchModel() {
    }
    
    public PageSearchModel(Hub<Page> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<Page> getHub() {
        if (hub == null) {
            hub = new Hub<Page>(Page.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<Page> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<Page> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    PageSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<Page> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(Page.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, Page> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, Page> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public PageSearch getPageSearch() {
        if (pageSearch != null) return pageSearch;
        pageSearch = new PageSearch();
        return pageSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<PageSearch> getPageSearchHub() {
        if (hubPageSearch == null) {
            hubPageSearch = new Hub<PageSearch>(PageSearch.class);
            hubPageSearch.add(getPageSearch());
            hubPageSearch.setPos(0);
        }
        return hubPageSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses PageSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<Page> sel = getPageSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(Page page, Hub<Page> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<Page> hub) {
    }
}

