// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class ProjectInfoSearchModel {
    private static Logger LOG = Logger.getLogger(ProjectInfoSearchModel.class.getName());
    
    protected Hub<ProjectInfo> hub;  // search results
    protected Hub<ProjectInfo> hubMultiSelect;
    protected Hub<ProjectInfo> hubSearchFrom;  // hub (optional) to search from
    protected Hub<ProjectInfoSearch> hubProjectInfoSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, ProjectInfo> finder;
    
    // object used for search data
    protected ProjectInfoSearch projectInfoSearch;
    
    public ProjectInfoSearchModel() {
    }
    
    public ProjectInfoSearchModel(Hub<ProjectInfo> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<ProjectInfo> getHub() {
        if (hub == null) {
            hub = new Hub<ProjectInfo>(ProjectInfo.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<ProjectInfo> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<ProjectInfo> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    ProjectInfoSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<ProjectInfo> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(ProjectInfo.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, ProjectInfo> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, ProjectInfo> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public ProjectInfoSearch getProjectInfoSearch() {
        if (projectInfoSearch != null) return projectInfoSearch;
        projectInfoSearch = new ProjectInfoSearch();
        return projectInfoSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<ProjectInfoSearch> getProjectInfoSearchHub() {
        if (hubProjectInfoSearch == null) {
            hubProjectInfoSearch = new Hub<ProjectInfoSearch>(ProjectInfoSearch.class);
            hubProjectInfoSearch.add(getProjectInfoSearch());
            hubProjectInfoSearch.setPos(0);
        }
        return hubProjectInfoSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses ProjectInfoSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<ProjectInfo> sel = getProjectInfoSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(ProjectInfo projectInfo, Hub<ProjectInfo> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<ProjectInfo> hub) {
    }
}

