// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class SectionSearchModel {
    private static Logger LOG = Logger.getLogger(SectionSearchModel.class.getName());
    
    protected Hub<Section> hub;  // search results
    protected Hub<Section> hubMultiSelect;
    protected Hub<Section> hubSearchFrom;  // hub (optional) to search from
    protected Hub<SectionSearch> hubSectionSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, Section> finder;
    
    // object used for search data
    protected SectionSearch sectionSearch;
    
    public SectionSearchModel() {
    }
    
    public SectionSearchModel(Hub<Section> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<Section> getHub() {
        if (hub == null) {
            hub = new Hub<Section>(Section.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<Section> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<Section> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    SectionSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<Section> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(Section.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, Section> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, Section> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public SectionSearch getSectionSearch() {
        if (sectionSearch != null) return sectionSearch;
        sectionSearch = new SectionSearch();
        return sectionSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<SectionSearch> getSectionSearchHub() {
        if (hubSectionSearch == null) {
            hubSectionSearch = new Hub<SectionSearch>(SectionSearch.class);
            hubSectionSearch.add(getSectionSearch());
            hubSectionSearch.setPos(0);
        }
        return hubSectionSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses SectionSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<Section> sel = getSectionSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(Section section, Hub<Section> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<Section> hub) {
    }
}

