// Generated by OABuilder
package com.viaoa.docbuilder.model.search;

import java.util.logging.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class TutorialSearchModel {
    private static Logger LOG = Logger.getLogger(TutorialSearchModel.class.getName());
    
    protected Hub<Tutorial> hub;  // search results
    protected Hub<Tutorial> hubMultiSelect;
    protected Hub<Tutorial> hubSearchFrom;  // hub (optional) to search from
    protected Hub<TutorialSearch> hubTutorialSearch;  // search data, size=1, AO
    
    // finder used to find objects in a path
    protected OAFinder<?, Tutorial> finder;
    
    // object used for search data
    protected TutorialSearch tutorialSearch;
    
    public TutorialSearchModel() {
    }
    
    public TutorialSearchModel(Hub<Tutorial> hub) {
        this.hub = hub;
    }
    
    // hub used for search results
    public Hub<Tutorial> getHub() {
        if (hub == null) {
            hub = new Hub<Tutorial>(Tutorial.class);
        }
        return hub;
    }
    
    // hub used to search within
    private HubListener hlSearchFromHub;
    public Hub<Tutorial> getSearchFromHub() {
        return hubSearchFrom;
    }
    public void setSearchFromHub(Hub<Tutorial> hub) {
        if (this.hlSearchFromHub != null) {
            hubSearchFrom.removeListener(hlSearchFromHub);
            hlSearchFromHub = null;
        }
    
        hubSearchFrom = hub;
        if (hubSearchFrom != null) {
            hlSearchFromHub = new HubListenerAdapter() {
                @Override
                public void onNewList(HubEvent e) {
                    TutorialSearchModel.this.getHub().clear();
                }
            };
            hubSearchFrom.addHubListener(hlSearchFromHub);
        }
    }
    public void close() {
        setSearchFromHub(null);
    }
    
    public Hub<Tutorial> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<>(Tutorial.class);
        }
        return hubMultiSelect;
    }
    
    public OAFinder<?, Tutorial> getFinder() {
        return finder;
    }
    public void setFinder(OAFinder<?, Tutorial> finder) {
        this.finder = finder;
    }
    
    // object used to input query data, to be used by searchHub
    public TutorialSearch getTutorialSearch() {
        if (tutorialSearch != null) return tutorialSearch;
        tutorialSearch = new TutorialSearch();
        return tutorialSearch;
    }
    
    // hub for search object - used to bind with UI components for entering search data
    public Hub<TutorialSearch> getTutorialSearchHub() {
        if (hubTutorialSearch == null) {
            hubTutorialSearch = new Hub<TutorialSearch>(TutorialSearch.class);
            hubTutorialSearch.add(getTutorialSearch());
            hubTutorialSearch.setPos(0);
        }
        return hubTutorialSearch;
    }
    
    
    
    public void beforeInput() {
        // hook that is called before search input starts
    }
    
    // uses TutorialSearch to build query, and populate Hub 
    public void performSearch() {
        OASelect<Tutorial> sel = getTutorialSearch().getSelect();
        sel.setSearchHub(getSearchFromHub());
        sel.setFinder(getFinder());
        getHub().select(sel);
    }
    
    // can to overwritten to know when a selection is made
    public void onSelect(Tutorial tutorial, Hub<Tutorial> hub) {
    }
    // can to overwritten to know when a multi-select is made
    public void onSelect(Hub<Tutorial> hub) {
    }
}

