// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.docbuilder.model.oa.*;
 
public class ClassInfoPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public ClassInfoPPx(String name) {
        this(null, name);
    }

    public ClassInfoPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public PackageInfoPPx packageInfo() {
        PackageInfoPPx ppx = new PackageInfoPPx(this, ClassInfo.P_PackageInfo);
        return ppx;
    }

    public PagePPx page() {
        PagePPx ppx = new PagePPx(this, ClassInfo.P_Page);
        return ppx;
    }

    public PagePPx referencePages() {
        PagePPx ppx = new PagePPx(this, ClassInfo.P_ReferencePages);
        return ppx;
    }

    public String id() {
        return pp + "." + ClassInfo.P_Id;
    }

    public String created() {
        return pp + "." + ClassInfo.P_Created;
    }

    public String name() {
        return pp + "." + ClassInfo.P_Name;
    }

    public String core() {
        return pp + "." + ClassInfo.P_Core;
    }

    public String doc() {
        return pp + "." + ClassInfo.P_Doc;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
