// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class CodePP {
    private static PagePPx page;
     

    public static PagePPx page() {
        if (page == null) page = new PagePPx(Code.P_Page);
        return page;
    }

    public static String id() {
        String s = Code.P_Id;
        return s;
    }

    public static String created() {
        String s = Code.P_Created;
        return s;
    }

    public static String code() {
        String s = Code.P_Code;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
