// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class ImageStorePP {
    private static PagePPx pages;
     

    public static PagePPx pages() {
        if (pages == null) pages = new PagePPx(ImageStore.P_Pages);
        return pages;
    }

    public static String id() {
        String s = ImageStore.P_Id;
        return s;
    }

    public static String created() {
        String s = ImageStore.P_Created;
        return s;
    }

    public static String bytes() {
        String s = ImageStore.P_Bytes;
        return s;
    }

    public static String origFileName() {
        String s = ImageStore.P_OrigFileName;
        return s;
    }

    public static String drawioLink() {
        String s = ImageStore.P_DrawioLink;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
