// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.docbuilder.model.oa.*;
 
public class PackageInfoPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public PackageInfoPPx(String name) {
        this(null, name);
    }

    public PackageInfoPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ClassInfoPPx classInfos() {
        ClassInfoPPx ppx = new ClassInfoPPx(this, PackageInfo.P_ClassInfos);
        return ppx;
    }

    public PackageInfoPPx packageInfos() {
        PackageInfoPPx ppx = new PackageInfoPPx(this, PackageInfo.P_PackageInfos);
        return ppx;
    }

    public PagePPx page() {
        PagePPx ppx = new PagePPx(this, PackageInfo.P_Page);
        return ppx;
    }

    public PackageInfoPPx parentPackageInfo() {
        PackageInfoPPx ppx = new PackageInfoPPx(this, PackageInfo.P_ParentPackageInfo);
        return ppx;
    }

    public ProjectInfoPPx projectInfo() {
        ProjectInfoPPx ppx = new ProjectInfoPPx(this, PackageInfo.P_ProjectInfo);
        return ppx;
    }

    public String id() {
        return pp + "." + PackageInfo.P_Id;
    }

    public String created() {
        return pp + "." + PackageInfo.P_Created;
    }

    public String packageName() {
        return pp + "." + PackageInfo.P_PackageName;
    }

    public String seq() {
        return pp + "." + PackageInfo.P_Seq;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
