// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class PagePP {
    private static ClassInfoPPx classInfo;
    private static CodePPx codes;
    private static ImageStorePPx imageStores;
    private static LinkInfoPPx linkInfos;
    private static PackageInfoPPx packageInfo;
    private static ProjectInfoPPx projectInfo;
    private static ClassInfoPPx referenceClassInfos;
    private static SectionPPx section;
     

    public static ClassInfoPPx classInfo() {
        if (classInfo == null) classInfo = new ClassInfoPPx(Page.P_ClassInfo);
        return classInfo;
    }

    public static CodePPx codes() {
        if (codes == null) codes = new CodePPx(Page.P_Codes);
        return codes;
    }

    public static ImageStorePPx imageStores() {
        if (imageStores == null) imageStores = new ImageStorePPx(Page.P_ImageStores);
        return imageStores;
    }

    public static LinkInfoPPx linkInfos() {
        if (linkInfos == null) linkInfos = new LinkInfoPPx(Page.P_LinkInfos);
        return linkInfos;
    }

    public static PackageInfoPPx packageInfo() {
        if (packageInfo == null) packageInfo = new PackageInfoPPx(Page.P_PackageInfo);
        return packageInfo;
    }

    public static ProjectInfoPPx projectInfo() {
        if (projectInfo == null) projectInfo = new ProjectInfoPPx(Page.P_ProjectInfo);
        return projectInfo;
    }

    public static ClassInfoPPx referenceClassInfos() {
        if (referenceClassInfos == null) referenceClassInfos = new ClassInfoPPx(Page.P_ReferenceClassInfos);
        return referenceClassInfos;
    }

    public static SectionPPx section() {
        if (section == null) section = new SectionPPx(Page.P_Section);
        return section;
    }

    public static String id() {
        String s = Page.P_Id;
        return s;
    }

    public static String created() {
        String s = Page.P_Created;
        return s;
    }

    public static String seq() {
        String s = Page.P_Seq;
        return s;
    }

    public static String name() {
        String s = Page.P_Name;
        return s;
    }

    public static String doc() {
        String s = Page.P_Doc;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
