// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.docbuilder.model.oa.*;
 
public class PagePPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public PagePPx(String name) {
        this(null, name);
    }

    public PagePPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public ClassInfoPPx classInfo() {
        ClassInfoPPx ppx = new ClassInfoPPx(this, Page.P_ClassInfo);
        return ppx;
    }

    public CodePPx codes() {
        CodePPx ppx = new CodePPx(this, Page.P_Codes);
        return ppx;
    }

    public ImageStorePPx imageStores() {
        ImageStorePPx ppx = new ImageStorePPx(this, Page.P_ImageStores);
        return ppx;
    }

    public LinkInfoPPx linkInfos() {
        LinkInfoPPx ppx = new LinkInfoPPx(this, Page.P_LinkInfos);
        return ppx;
    }

    public PackageInfoPPx packageInfo() {
        PackageInfoPPx ppx = new PackageInfoPPx(this, Page.P_PackageInfo);
        return ppx;
    }

    public ProjectInfoPPx projectInfo() {
        ProjectInfoPPx ppx = new ProjectInfoPPx(this, Page.P_ProjectInfo);
        return ppx;
    }

    public ClassInfoPPx referenceClassInfos() {
        ClassInfoPPx ppx = new ClassInfoPPx(this, Page.P_ReferenceClassInfos);
        return ppx;
    }

    public SectionPPx section() {
        SectionPPx ppx = new SectionPPx(this, Page.P_Section);
        return ppx;
    }

    public String id() {
        return pp + "." + Page.P_Id;
    }

    public String created() {
        return pp + "." + Page.P_Created;
    }

    public String seq() {
        return pp + "." + Page.P_Seq;
    }

    public String name() {
        return pp + "." + Page.P_Name;
    }

    public String doc() {
        return pp + "." + Page.P_Doc;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
