// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class ProjectInfoPP {
    private static PackageInfoPPx packageInfos;
    private static PagePPx page;
     

    public static PackageInfoPPx packageInfos() {
        if (packageInfos == null) packageInfos = new PackageInfoPPx(ProjectInfo.P_PackageInfos);
        return packageInfos;
    }

    public static PagePPx page() {
        if (page == null) page = new PagePPx(ProjectInfo.P_Page);
        return page;
    }

    public static String id() {
        String s = ProjectInfo.P_Id;
        return s;
    }

    public static String created() {
        String s = ProjectInfo.P_Created;
        return s;
    }

    public static String name() {
        String s = ProjectInfo.P_Name;
        return s;
    }

    public static String directory() {
        String s = ProjectInfo.P_Directory;
        return s;
    }

    public static String console() {
        String s = ProjectInfo.P_Console;
        return s;
    }

    public static String loadClasses() {
        String s = "loadClasses";
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
