// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class SectionPP {
    private static PagePPx page;
    private static SectionPPx parentSection;
    private static SectionPPx sections;
    private static TutorialPPx tutorial;
     

    public static PagePPx page() {
        if (page == null) page = new PagePPx(Section.P_Page);
        return page;
    }

    public static SectionPPx parentSection() {
        if (parentSection == null) parentSection = new SectionPPx(Section.P_ParentSection);
        return parentSection;
    }

    public static SectionPPx sections() {
        if (sections == null) sections = new SectionPPx(Section.P_Sections);
        return sections;
    }

    public static TutorialPPx tutorial() {
        if (tutorial == null) tutorial = new TutorialPPx(Section.P_Tutorial);
        return tutorial;
    }

    public static String id() {
        String s = Section.P_Id;
        return s;
    }

    public static String created() {
        String s = Section.P_Created;
        return s;
    }

    public static String seq() {
        String s = Section.P_Seq;
        return s;
    }

    public static String name() {
        String s = Section.P_Name;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
