// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import com.viaoa.docbuilder.model.oa.*;
 
public class TutorialPP {
    private static SectionPPx sections;
     

    public static SectionPPx sections() {
        if (sections == null) sections = new SectionPPx(Tutorial.P_Sections);
        return sections;
    }

    public static String id() {
        String s = Tutorial.P_Id;
        return s;
    }

    public static String created() {
        String s = Tutorial.P_Created;
        return s;
    }

    public static String name() {
        String s = Tutorial.P_Name;
        return s;
    }

    public static String pp() {
        return ""; // this
    }
}
 
