// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.propertypath;
 
import java.io.Serializable;
import com.viaoa.docbuilder.model.oa.*;
 
public class TutorialPPx implements PPxInterface, Serializable {
    private static final long serialVersionUID = 1L;
    public final String pp;  // propertyPath
     
    public TutorialPPx(String name) {
        this(null, name);
    }

    public TutorialPPx(PPxInterface parent, String name) {
        String s = null;
        if (parent != null) {
            s = parent.toString();
        }
        if (s == null) s = "";
        if (name != null && name.length() > 0) {
            if (s.length() > 0 && name.charAt(0) != ':') s += ".";
            s += name;
        }
        pp = s;
    }

    public SectionPPx sections() {
        SectionPPx ppx = new SectionPPx(this, Tutorial.P_Sections);
        return ppx;
    }

    public String id() {
        return pp + "." + Tutorial.P_Id;
    }

    public String created() {
        return pp + "." + Tutorial.P_Created;
    }

    public String name() {
        return pp + "." + Tutorial.P_Name;
    }

    @Override
    public String toString() {
        return pp;
    }
    public String pp() {
        return pp;
    }
}
 
