// Copied from OATemplate project by OABuilder 06/20/21 11:44 AM
// Generated by OABuilder 06/20/21 11:44 AM

package com.viaoa.docbuilder.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.delegate.*;
import com.viaoa.docbuilder.delegate.oa.*;
import com.viaoa.docbuilder.resource.Resource;
import com.viaoa.docbuilder.view.*;

public class AppUserErrorJfc extends AppUserErrorJfcBase {
    
    public AppUserErrorJfc() {
    }
    
    public AppUserErrorJfc(Hub<AppUserError> hubAppUserError) {
        super(hubAppUserError);
    }
    
    public AppUserErrorJfc(AppUserErrorModel modelAppUserError) {
        super(modelAppUserError);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

