// Generated by OABuilder 06/20/21 09:55 PM

package com.viaoa.docbuilder.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.delegate.*;
import com.viaoa.docbuilder.delegate.oa.*;
import com.viaoa.docbuilder.resource.Resource;
import com.viaoa.docbuilder.view.*;

public class ImageStoreJfc extends ImageStoreJfcBase {
    
    public ImageStoreJfc() {
    }
    
    public ImageStoreJfc(Hub<ImageStore> hubImageStore) {
        super(hubImageStore);
    }
    
    public ImageStoreJfc(ImageStoreModel modelImageStore) {
        super(modelImageStore);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

