// Generated by OABuilder 06/21/21 03:27 PM

package com.viaoa.docbuilder.view.oa;

import javax.swing.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.delegate.*;
import com.viaoa.docbuilder.delegate.oa.*;
import com.viaoa.docbuilder.resource.Resource;
import com.viaoa.docbuilder.view.*;

public class LinkInfoJfc extends LinkInfoJfcBase {
    
    public LinkInfoJfc() {
    }
    
    public LinkInfoJfc(Hub<LinkInfo> hubLinkInfo) {
        super(hubLinkInfo);
    }
    
    public LinkInfoJfc(LinkInfoModel modelLinkInfo) {
        super(modelLinkInfo);
    }
    
    // CUSTOM code here
    /*$$Start: Jfc.custom $$*/
    /*$$End: Jfc.custom $$*/
    
}

