// Generated by OABuilder 

package com.viaoa.docbuilder.view.oa;

import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.awt.Dialog.*;
import java.lang.ref.WeakReference;
import java.util.*;
import java.util.Map.Entry;
import java.util.logging.*;
import java.util.concurrent.atomic.AtomicInteger;

import javax.swing.*;
import javax.swing.border.*;
import javax.swing.text.*;
import javax.swing.event.*;

import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.jfc.*;
import com.viaoa.jfc.OAButton.*;
import com.viaoa.jfc.border.*;
import com.viaoa.jfc.control.*;
import com.viaoa.jfc.table.*;
import com.viaoa.jfc.text.*;
import com.viaoa.image.*;
import com.viaoa.jfcapp.*;
import com.viaoa.model.oa.VInteger;
import com.viaoa.util.*;

import com.viaoa.docbuilder.model.*;
import com.viaoa.docbuilder.model.search.*;
import com.viaoa.docbuilder.model.oa.PackageInfo;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.custom.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.delegate.*;
import com.viaoa.docbuilder.delegate.oa.*;
import com.viaoa.docbuilder.resource.Resource;
import com.viaoa.docbuilder.view.*;

public class PackageInfoJfcBase implements OAModelJfcInterface {
    protected static Logger LOG = Logger.getLogger(PackageInfoJfc.class.getName());
    
    public static final String PP_Display    = OAString.cpp(PackageInfo.P_PackageName);
    public static final String PP_Icon       = null;
    public static final String PP_Image      = null;
    public static final String PP_ForeColor  = null;
    public static final String PP_BackColor  = null;
    public static final String PP_IconColor  = null;
    public static final String PP_Font       = null;
    // Model
    protected PackageInfoModel model;
    
    // Tree
    protected OATreeNode lastTreeNode;  // used by getTreeUsed()
    protected OATreeTitleNode titleNode;
    protected OATreeNode node;
    
    // ComboBox
    protected OAComboBox cbo;
    protected OATableComboBox cboTable;
    
    // List
    protected OAList lst;
    
    // edit dialog
    private WeakReference<JDialog> wrEditDialog;
    
    // Card Panel
    public static final String CARD_List = "list";
    public static final String CARD_Edit = "edit";
    protected static final String CARD_ClassInfos = "ClassInfos";
    protected static final String CARD_PackageInfos = "PackageInfos";
    protected int TAB_ClassInfos = -1;
    protected int TAB_PackageInfos = -1;
    protected JPanel cardPanel;
    protected CardLayout cardLayout;
    protected JTabbedPane tabbedPane;
    public static final String TABLETYPE_Original = "Original";
    public static final String TABLETYPE_TreeTable = "TreeTable";
    public static final String TABLETYPE_Root = "Root";
    public static final String TABLETYPE_Flattened = "Flattened";
    public static final String TABLETYPE_Recursive = "Recursive";
    
    protected JPanel panCardTable;
    protected CardLayout cardLayoutTable;
    
    
    // Search
    protected PackageInfoSearchJfc jfcSearch;
    // hub Search
    protected PackageInfoSearchJfc jfcSearchHub;
    // Add
    protected PackageInfoSearchJfc jfcAdd;
    
    
    // focus components
    protected OADateTimeTextField dttxtCreated;
    protected OADateTimeTextField tableDtTxtCreated;
    protected PageJfc jfcPage;
    protected PackageInfoJfc jfcParentPackageInfo;
    protected ProjectInfoJfc jfcProjectInfo;
    protected ClassInfoJfc jfcClassInfos;
    protected PackageInfoJfc jfcPackageInfos;
    
    public PackageInfoJfcBase() {
        this.model = new PackageInfoModel();
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    
    public PackageInfoJfcBase(Hub<PackageInfo> hubPackageInfo) {
        this.model = new PackageInfoModel(hubPackageInfo);
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    public PackageInfoJfcBase(PackageInfoModel modelPackageInfo) {
        if (modelPackageInfo == null) this.model = new PackageInfoModel();
        else this.model = modelPackageInfo;
        this.model.setForJfc(true);
        OAModelJfcUtil.register(this);
    }
    
    // Hub
    public Hub<PackageInfo> getHub() {
        return model.getHub();
    }
    
    private int level;
    public int getLevel() {
        return this.level;
    }
    public void setLevel(int level) {
        this.level = level;
    }
    
    
    // Model
    public PackageInfoModel getModel() {
        return model;
    }
    
    
    
    // Images
    public static Icon getIcon() {
        return Resource.getJarIcon("packageInfo.gif");
    }
    public static Icon getTitleIcon() {
        return Resource.getJarIcon("packageInfos.gif");
    }
    
    // Tree
    public OATree getTreeUsed() {
        if (lastTreeNode != null) return lastTreeNode.getTree();
        return null;
    }
    protected void setLastTreeNode(OATreeNode tn) {
        if (lastTreeNode == null || lastTreeNode.getTree() == null) {
            lastTreeNode = tn;
        }
    }
    public OATreeTitleNode getTreeTitleNode() {
        if (titleNode == null) {
            titleNode = createTreeTitleNode();
        }
        return titleNode;
    }
    
    public OATreeTitleNode createTreeTitleNode() {
        OATreeTitleNode treeTitleNode = new OATreeTitleNode(getModel().getPluralDisplayName()) {
            @Override
            public void objectSelected(Object obj) {
                super.objectSelected(obj);
                onShowListPanel();
            }
            JLabel lbl;
            @Override
            public Component getTreeCellRendererComponent(Component comp,
                JTree tree, Object value, boolean selected,
                boolean expanded, boolean leaf, int row, boolean hasFocus)
            {
                comp = super.getTreeCellRendererComponent(comp, tree, value, selected, expanded, leaf, row, hasFocus);
                if (lbl == null) {
                    if (comp instanceof JLabel) lbl = (JLabel) comp;
                }
                if (lbl != null) lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
                return comp;
            }
        };
        treeTitleNode.setCountHub(getModel().getRootHub());
        treeTitleNode.setIcon(getTitleIcon());
        treeTitleNode.setPopupMenu(createTreeTitleNodePopupMenu(treeTitleNode));
        treeTitleNode.setMaxImageHeight(20);
        treeTitleNode.setMaxImageWidth(32);
        setLastTreeNode(treeTitleNode);
        return treeTitleNode;
     }
    
    public JPopupMenu createTreeTitleNodePopupMenu(OATreeNode tn) {
        JPopupMenu menu = new JPopupMenu();
    
        JMenuItem miSearch = createSearchMenuItem();
        if (miSearch != null) menu.add(miSearch);
        JMenuItem miNew = createNewMenuItem();
        if (miNew != null) menu.add(miNew);
        JMenuItem miInsert = createInsertMenuItem();
        if (miInsert != null) menu.add(miInsert);
        if (miSearch != null || miNew != null) menu.addSeparator();
        JMenuItem miPaste = createPasteMenuItem();
        if (miPaste != null) {
            menu.add(miPaste);
            menu.addSeparator();
        }
    
        menu.add(createCollapseOthersMenuItem(tn));
        return menu;
    }
    
    public OAMenuItem createAddMenuItem() {
        if (!getModel().getAllowAdd()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAButton.ADD_MANUAL) {
            @Override
            public boolean onActionPerformed() {
                PackageInfoJfcBase.this.onAdd();
                return true;
            }
        };
        mi.setText("Add a "+getModel().getDisplayName());
        mi.setToolTipText("Add a "+getModel().getDisplayName());
        return mi;
    }
    
    public OAMenuItem createNewMenuItem() {
        return createNewMenuItem(getHub());
    }
    public OAMenuItem createNewMenuItem(Hub<PackageInfo> hub) {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(hub, OAMenuItem.NEW) {
            @Override
            public void afterActionPerformed() {
                // PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                PackageInfoJfcBase.this.onNewPackageInfoCreated();
                super.afterActionPerformed();
            }
        };
        mi.setMnemonic(KeyEvent.VK_N);
        mi.setText("Create a new "+getModel().getDisplayName());
        mi.setToolTipText("Create a new "+getModel().getDisplayName());
        mi.setFocusComponent(dttxtCreated);
        return mi;
    }
    
    public OAMenuItem createInsertMenuItem() {
        return createInsertMenuItem(getHub());
    }
    public OAMenuItem createInsertMenuItem(Hub<PackageInfo> hub) {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(hub, OAMenuItem.INSERT) {
            @Override
            public void afterActionPerformed() {
                // PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                PackageInfoJfcBase.this.onNewPackageInfoCreated();
                super.afterActionPerformed();
            }
        };
        mi.setMnemonic(KeyEvent.VK_I);
        mi.setText("Insert a new "+getModel().getDisplayName());
        mi.setToolTipText("Insert a new "+getModel().getDisplayName());
        mi.setFocusComponent(dttxtCreated);
        return mi;
    }
    
    public JMenuItem createCollapseOthersMenuItem(final OATreeNode tn) {
        JMenuItem mi = new JMenuItem();
        mi.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                OATree t = tn.getTree();
                if (t != null) {
                    t.expandOnlySelectedTreeNode();
                }
            }
        });
        mi.setMnemonic(KeyEvent.VK_C);
        mi.setText("Collapse others");
        mi.setToolTipText("Collapse other tree nodes");
        return mi;
    }
    public OATreeNode getTreeNode() {
        if (node != null) return node;
        node = createTreeNode(null, null, true);
        return node;
    }
    public OATreeNode createTreeNode(String leadingPropertyPath, Hub<PackageInfo> hubRoot, boolean bIncludeChildren, OATreeNode ... parentNodes) {
        if (hubRoot == null && OAString.isEmpty(leadingPropertyPath)) {
            hubRoot = getModel().getRootHub();
        }
        OATreeNode node = new OATreeNode(OAString.cpp(leadingPropertyPath, PackageInfo.P_PackageName), hubRoot, getModel().getRecursiveHub()) {
            @Override
            public void objectSelected(Object obj) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_Recursive);
                super.objectSelected(obj);
                PackageInfoJfcBase.this.onShowEditPanel();
            }
            @Override
            public void onDoubleClick(Object obj, MouseEvent e) {
                PackageInfoJfcBase.this.onDoubleClickTreeNode();
            }
            @Override
            public JPopupMenu getPopupMenu() {
                JPopupMenu pm = super.getPopupMenu();
                if (pm == null) {
                    pm = createTreeNodePopupMenu(this);
                    setPopupMenu(pm);
                }
                return pm;
            }
        };
        node.setIcon(getIcon());
        node.setForegroundColorProperty(PP_ForeColor);
        node.setBackgroundColorProperty(PP_BackColor);
        node.setIconColorProperty(PP_IconColor);
        node.setImageProperty(PP_Icon);
        node.setAllowDnD(true);
        node.setAllowDrop(true);
        node.setAllowDrag(true);
        node.setFontProperty(PP_Font);
        node.setSuffix(null);
        node.setMaxImageHeight(20);
        node.setMaxImageWidth(32);
        setLastTreeNode(node);
        if (getModel().getAllowMultiSelect()) {
            node.setSelectedHub(getModel().getMultiSelectHub());
        }
    
        if (!bIncludeChildren) {
            node.add(node, PackageInfo.P_PackageInfos);
            return node;
        }
     
        OATreeNode[] nodes = (OATreeNode[]) OAArray.add(OATreeNode.class, parentNodes, node);
        OATreeTitleNode ttn;
        OATreeNode node2;
        ttn = getClassInfosJfc().getTreeTitleNode();
        node2 = findNode(PackageInfo.P_ClassInfos, parentNodes);
        if (node2 == null) {
            node2 = getClassInfosJfc().createTreeNode(PackageInfo.P_ClassInfos, null, true, nodes);
            node2.setAllowDnd(false);
        }
        ttn.add(node2);
        node.add(ttn);
     
        node.add(node, PackageInfo.P_PackageInfos);
        return node;
    }
    protected OATreeNode findNode(String propertyPath, OATreeNode ... parentNodes) {
        if (propertyPath == null) return null;
        for (OATreeNode tn : parentNodes) {
            if (tn.getHub() != null) continue;
            String pp = tn.getPropertyPath();
            if (pp == null) continue;
            if (pp.toLowerCase().startsWith(propertyPath.toLowerCase()+".")) return tn;
        }
        return null;
    }
    
    public JPopupMenu createTreeNodePopupMenu(OATreeNode tn) {
        JPopupMenu menu = new JPopupMenu();
    
        JMenuItem miSearch = createSearchMenuItem();
        if (miSearch != null) menu.add(miSearch);
        JMenuItem miNew = createNewMenuItem();
        if (miNew != null) menu.add(miNew);
        JMenuItem miInsert = createInsertMenuItem();
        if (miInsert != null) menu.add(miInsert);
        if (miSearch != null || miNew != null) menu.addSeparator();
    
        OAMenuItem mi;
        mi = getClassInfosJfc().createNewMenuItem();
        if (mi != null) menu.add(mi);
        mi = getClassInfosJfc().createAddMenuItem();
        if (mi != null) menu.add(mi);
    
        menu.addSeparator();
        JMenuItem miRemove = createRemoveMenuItem();
        if (miRemove != null) menu.add(miRemove);
        JMenuItem miDelete = createDeleteMenuItem();
        if (miDelete != null) menu.add(miDelete);
    
        if (miRemove != null || miDelete != null) menu.addSeparator();
        JMenuItem miCut = createCutMenuItem();
    
        if (miCut != null) menu.add(miCut);
        JMenuItem miCopy = createCopyMenuItem();
        if (miCopy != null) menu.add(miCopy);
        JMenuItem miPaste = createPasteMenuItem();
        if (miPaste != null) menu.add(miPaste);
    
        if (miCut != null || miCopy != null || miPaste != null) menu.addSeparator();
    
        JMenuItem miCollapse = createCollapseOthersMenuItem(tn);
        if (miCollapse != null) menu.add(miCollapse);
    
        return menu;
    }
    public OAMenuItem createSearchMenuItem() {
        if (!getModel().getAllowSearch()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), getModel().getDisplayName() + " search ...", Resource.getJarIcon("search.gif"), OAButton.SEARCH) {
            @Override
            public Object getSearchObject() {
                PackageInfo packageInfo = PackageInfoJfcBase.this.onSearch();
                return packageInfo;
            }
            @Override
            public void afterActionPerformed() {
                super.afterActionPerformed();
                OATree tree = getTreeUsed();
                if (tree != null) {
                    tree.setSelectedNode(getHub().getAO());
                }
                onShowEditPanel();
            }
        };
        mi.setMnemonic(KeyEvent.VK_S);
        return mi;
    }
    
    public JMenuItem createHubSearchMenuItem() {
        if (!getModel().getAllowHubSearch()) return null;
        JMenuItem mi = new JMenuItem(getModel().getDisplayName() + " table search ...", Resource.getJarIcon("hubsearch16.png"));
        mi.setMnemonic(KeyEvent.VK_I);
        mi.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.onHubSearch();
           }
        });
        return mi;
    }
    public OAMenuItem createCutMenuItem() {
        if (!getModel().getAllowCut()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.CUT);
        mi.setText("Cut "+getModel().getDisplayName());
        if (getModel().getAllowMultiSelect()) {
            mi.setMultiSelectHub(getModel().getMultiSelectHub());
        }
        return mi;
    }
    public OAMenuItem createCopyMenuItem() {
        if (!getModel().getAllowCopy()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.COPY);
        mi.setText("Copy "+getModel().getDisplayName());
        mi.setToolTipText("Create a copy of "+getModel().getDisplayName());
        if (getModel().getAllowMultiSelect()) {
            mi.setMultiSelectHub(getModel().getMultiSelectHub());
        }
        return mi;
    }
    public OAMenuItem createPasteMenuItem() {
        if (!getModel().getAllowPaste()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.PASTE);
        mi.setText("Paste "+getModel().getDisplayName());
        mi.setToolTipText("Paste "+getModel().getDisplayName());
        mi.setConfirmMessage("Ok to paste?");
        return mi;
    }
    public OAMenuItem createSaveMenuItem() {
        if (!getModel().getAllowSave()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.SAVE);
        mi.setText("Save "+getModel().getDisplayName());
        mi.setMnemonic(KeyEvent.VK_S);
        mi.setToolTipText("Save "+getModel().getDisplayName());
        return mi;
    }
    public OAMenuItem createDeleteMenuItem() {
        if (!getModel().getAllowDelete()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.DELETE);
        mi.setText("Delete "+getModel().getDisplayName()+" ...");
        mi.setConfirmMessage("OK to Delete this "+getModel().getDisplayName()+" from system?");
        mi.setMnemonic(KeyEvent.VK_D);
        mi.setUseSwingWorker(true);
        mi.setProcessingText("Processing ...", "Please wait while deleting Client");
        // mi.setToolTipText("Delete "+getModel().getDisplayName()+" from system, must be an Admin to do this.");
        return mi;
    }
    public OAMenuItem createRemoveMenuItem() {
        if (!getModel().getAllowRemove()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.REMOVE);
        mi.setText("Remove "+getModel().getDisplayName()+" ...");
        mi.setToolTipText("remove "+getModel().getDisplayName()+" from the list");
        mi.setMnemonic(KeyEvent.VK_R);
        return mi;
    }
    
    // Label
    public OALabel createLabel() {
        OALabel lbl = new OALabel(getHub(), OAString.cpp(PackageInfo.P_PackageName), 20) {
            @Override
            public void customizeRenderer(JLabel lbl, Object object, Object value, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
                PackageInfoJfcBase.this.customizeRenderer(lbl, PackageInfoJfcBase.this.getHub().getAt(row), isSelected, hasFocus, row, wasChanged, wasMouseOver);
            }
            @Override
            public String getToolTipText(Object object, int row, String defaultValue) {
                return PackageInfoJfcBase.this.getToolTipText(PackageInfoJfcBase.this.getHub().getAt(row), row, defaultValue);
            }
        };
        lbl.setMaximumColumns(75);
        lbl.setMinimumColumns(10);
        lbl.setIconColorProperty(PP_IconColor);
        lbl.setImageProperty(PP_Icon);
        lbl.setFormat(null);
        lbl.setMaxImageHeight(20);
        lbl.setMaxImageWidth(32);
        lbl.setVerticalAlignment(SwingConstants.TOP);
        return lbl;
    }
    // used for Label, ComboBox
    protected void customizeRenderer(JLabel lbl, PackageInfo packageInfo, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
    }
    protected String getToolTipText(PackageInfo packageInfo, int row, String defaultValue) {
        return defaultValue;
    }
    
    // ComboBox
    public OAComboBox getComboBox() {
        if (cbo == null) {
            cbo = createComboBox();
        }
        return cbo;
    }
    
    public OAComboBox createComboBox() {
        OAComboBox cbo = new OAComboBox(getHub(), OAString.cpp(PackageInfo.P_PackageName), 20) {
            @Override
            public void customizeRenderer(JLabel lbl, Object object, Object value, boolean isSelected, boolean hasFocus, int row, boolean wasChanged, boolean wasMouseOver) {
                PackageInfoJfcBase.this.customizeRenderer(lbl, PackageInfoJfcBase.this.getHub().getAt(row), isSelected, hasFocus, row, wasChanged, wasMouseOver);
            }
            @Override
            public String getToolTipText(Object object, int row, String defaultValue) {
                return PackageInfoJfcBase.this.getToolTipText(PackageInfoJfcBase.this.getHub().getAt(row), row, defaultValue);
            }
        };
    
        cbo.setPopupColumns(35);
        cbo.setMaximumRowCount(15);
        cbo.setMaximumColumns(75);
        cbo.setMinimumColumns(10);
        cbo.setIconColorProperty(PP_IconColor);
        cbo.setImageProperty(PP_Icon);
        cbo.setFormat(null);
        cbo.setNullDescription("<html><i style='color:gray'>select</i></html>]");
        cbo.setMaxImageHeight(20);
        cbo.setMaxImageWidth(32);
        return cbo;
    }
    
    public OATableComboBox getTableComboBox() {
        if (cboTable == null) {
            cboTable = createTableComboBox();
        }
        return cboTable;
    }
    public OATableComboBox createTableComboBox() {
        OATable table = new OATable(getHub());
        table.setAllowDnD(false);
        table.setAllowSorting(false);
        table.addCounterColumn();
        getSearchJfc().createTableColumns(table);
        table.setPreferredSize(15, 4, true);
        table.resizeColumnsToFitHeading();
        
        OATableComboBox cboTable = new OATableComboBox(table, getHub(), PP_Display) {
            @Override
            public void onClear() {
                getHub().setAO(null);
            }
        };
        cboTable.allowClearButton(true);
        cboTable.setIconColorProperty(PP_IconColor);
        cboTable.setColumns(20);
        cboTable.setMaximumColumns(75);
        return cboTable;
    }
    
    
    // List
    public OAList getList() {
        if (lst == null) {
            lst = createList();
        }
        return lst;
    }
    public OAList createList() {
        OAList lst = new OAList(getHub(), OAString.cpp(PackageInfo.P_PackageName), 12, 20) {
            @Override
            public void customizeRenderer(JLabel label, JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
                super.customizeRenderer(label, list, value, index, isSelected, cellHasFocus);
                PackageInfoJfcBase.this.customizeRenderer(label, PackageInfoJfcBase.this.getHub().getAt(index), isSelected, cellHasFocus, index, false, false);
            }
        };
        lst.setMinimumColumns(6);
        lst.setMaximumColumns(75);
        lst.setAllowDnD(true);
        lst.setAllowRemove(true);
        lst.setAllowDelete(false);
        lst.setAllowInsert(false);
        lst.setImageProperty(null);
        lst.setMaxImageHeight(20);
        lst.setMaxImageWidth(32);
        lst.setIconColorProperty(PP_IconColor);
        lst.setBackgroundColorProperty(null);
        lst.setDoubleClickButton(null);
        if (model.getAllowMultiSelect()) {
            lst.setSelectionHub(getModel().getMultiSelectHub());
        }
        lst.setBorder(new EmptyBorder(3,3,1,1));
        
        return lst;
    }
    
    public JPanel createGrowingList() {
        OAList lst = createList();
        lst.setVisibleRowCount(1);
        lst.setBorder(new LineBorder(Color.gray, 1));
        
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(lst);
        
        JPanel panx = new JPanel(new FlowLayout(FlowLayout.LEFT, 2, 0));
        
        OAButton cmd = createGotoEditButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createAddButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createNewButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createDeleteButton();
        if (cmd != null) panx.add(cmd);
        
        cmd = createRemoveButton();
        if (cmd != null) panx.add(cmd);
        
        pan.add(panx, BorderLayout.SOUTH);
        return pan;
    }
    public OATree createRecursiveTree() {
        OATree tree = new OATree();
        tree.setPreferredSize(10, 24);
        tree.setAllowDnD(true);
        OATreeNode node, node2;
    
        node = new OATreeNode(PP_Display, getModel().getRootHub(), getModel().getRecursiveHub());
        tree.add(node);
    
        JMenuItem mi = createCutMenuItem();
        if (mi != null) {
            JPopupMenu menu = new JPopupMenu();
            menu.add(mi);
            menu.add(new OAMenuItem(getHub(), OAMenuItem.PASTE, "Paste after"));
            menu.add(new OAMenuItem(getHub().getDetailHub(PackageInfo.P_PackageInfos), OAMenuItem.PASTE, "Paste inside"));
            node.setPopupMenu(menu);
        }
    
        // make recursive
        node.add(node, PackageInfo.P_PackageInfos);
        return tree;
    }
    
    public OATable createRecursiveTreeTable() {
        final OATreeTableController tree = new OATreeTableController(getModel().getOriginalHub(), getModel().getFlattenedTreeTableHub(), getModel().getTreeTableHub());
        tree.setPreferredSize(15, 33);
        Dimension d = new Dimension(5,5);
        tree.setMinimumSize(d);
        tree.setPreferredSize(d);
        tree.setMaximumSize(d);
        
        OATreeNode node = new OATreeNode(PP_Display, getModel().getRootHub(), getModel().getRecursiveHub());
        tree.add(node);
        node.add(node, PackageInfo.P_PackageInfos); // make recursive
        
        OATable table = new OATable(getModel().getTreeTableHub());
        table.setAllowDnD(false);
        table.setAllowSorting(false);
        // table.setColumnProperties(ModelDelegate.getProperties(), "PackageInfo");
        
        table.addColumn("Package Info", 27, tree);
        PackageInfoJfc packageInfoJfc = new PackageInfoJfc(getModel().getTreeTableHub());
        packageInfoJfc.createTableColumns(table);
        table.setPreferredSize(6,2, false);
        table.allowDnD(true);
        return table;
    }
    // comboBoxTree
    public OATreeComboBox createSearchTreeComboBox() {
        OATreeComboBox cbo = new OATreeComboBox(createSearchTree(), getHub(), PP_Display);
        cbo.setColumns(20);
        return cbo;
    }
    public OATree createSearchTree() {
        OATree tree = new OATree();
        tree.setPreferredSize(10, 24);
        OATreeTitleNode tnode;
        OATreeNode node, node2;
    
        tnode = new OATreeTitleNode(getModel().getPluralDisplayName());
        tnode.setIcon(PackageInfoJfc.getTitleIcon());
        tree.add(tnode);
        node = new OATreeNode(PP_Display, getModel().getRootHub(), getModel().getRecursiveHub()) {
            @Override
            public void onDoubleClick(Object obj, MouseEvent e) {
                PackageInfoJfcBase.this.onDoubleClickTreeNode();
            }
        };
        if (getModel().getAllowMultiSelect()) {
            node.setSelectedHub(getModel().getMultiSelectHub());
        }
        node.setIcon(PackageInfoJfc.getIcon());
        node.setForegroundColorProperty(PackageInfoJfc.PP_ForeColor);
        node.setBackgroundColorProperty(PackageInfoJfc.PP_BackColor);
        node.setIconColorProperty(PackageInfoJfc.PP_IconColor);
        node.setImageProperty(PackageInfoJfc.PP_Icon);
        node.setFontProperty(PackageInfoJfc.PP_Font);
        node.setMaxImageHeight(20);
        node.setMaxImageWidth(32);
        tnode.add(node);
        node.add(node); // make recursive
        return tree;
    }
    
    
    // Table
    // this is to show multiple tables
    public JPanel createMainTableCardPanel() {
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(createTableCardPanel(false, false));
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createMainTableToolBar())), BorderLayout.NORTH);
        return pan;
    }
    public JPanel createDetailTableCardPanel() {
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(createTableCardPanel(false, true));
        pan.add(createToolBar(ToolBarOptions.createTableFindToolBar()), BorderLayout.NORTH);
        return pan;
    }
    
    public JPanel createTableCardPanel(boolean bIncludeNorthToolbar, boolean bIncludeSouthToolbar) {
        final CardLayout cardLayout = new CardLayout(5,5);
        final JPanel panTable = new JPanel(cardLayout);
        
        panTable.add(createTablePanel(bIncludeNorthToolbar, bIncludeSouthToolbar), TABLETYPE_Original);
        if (getModel().getAllowRecursive()) {
            panTable.add(createRecursiveTreeTablePanel(bIncludeNorthToolbar, bIncludeSouthToolbar), TABLETYPE_TreeTable);
            panTable.add(createTablePanel(bIncludeNorthToolbar, bIncludeSouthToolbar), TABLETYPE_Root);
            panTable.add(createTablePanel(bIncludeNorthToolbar, bIncludeSouthToolbar), TABLETYPE_Flattened);
            panTable.add(createTablePanel(bIncludeNorthToolbar, bIncludeSouthToolbar), TABLETYPE_Recursive);
        }
        getModel().addTypeListener(new HubListenerAdapter<VInteger>() {
            @Override
            public void afterPropertyChange(HubEvent<VInteger> e) {
                updateTableCardPanel(panTable, cardLayout);
            }
        });
        updateTableCardPanel(panTable, cardLayout);
        panTable.setMinimumSize(new Dimension(5,5));
        return panTable;
    }
    
    // change the table view/card that matches valid of model.Type
    private void updateTableCardPanel(JPanel panTable, CardLayout cardLayout) {
        switch (getModel().getType()) {
        case PackageInfoModel.TYPE_Original:
            cardLayout.show(panTable, TABLETYPE_Original);
            break;
        case PackageInfoModel.TYPE_TreeTable:
            cardLayout.show(panTable, TABLETYPE_TreeTable);
            break;
        case PackageInfoModel.TYPE_Root:
            cardLayout.show(panTable, TABLETYPE_Root);
            break;
        case PackageInfoModel.TYPE_Flattened:
            cardLayout.show(panTable, TABLETYPE_Flattened);
            break;
        case PackageInfoModel.TYPE_Recursive:
            cardLayout.show(panTable, TABLETYPE_Recursive);
            break;
        }
    }
    
    public JPanel createTablePanel() {
        return createTablePanel(true, true);
    }
    public JPanel createTablePanel(boolean bIncludeNorthToolbar, boolean bIncludeSouthToolbar) {
        OATable table = createTable();
        // table.setSelectHub(getModel().getMultiSelectHub());
    
        OATableScrollPane tableScrollPane = createTableScrollPane(table);
        tableScrollPane.setBorder(new TitledBorder(""));
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(tableScrollPane, BorderLayout.CENTER);
        
        if (bIncludeNorthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createTableFindToolBar());
            if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.NORTH);
        }
        if (bIncludeSouthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createSouthTableToolBar());
            if (toolBar != null) {
                pan.add(new OAScroller(toolBar), BorderLayout.SOUTH);
            }
        }
        return pan;
    }
    public JPanel createRecursiveTreeTablePanel() {
        return createRecursiveTreeTablePanel(true, true);
    }
    public JPanel createRecursiveTreeTablePanel(boolean bIncludeNorthToolbar, boolean bIncludeSouthToolbar) {
        OATable table = createRecursiveTreeTable();
        // table.setSelectHub(getModel().getMultiSelectHub());
        table.setComponentPopupMenu(createTablePopupMenu());
    
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(new JScrollPane(table), BorderLayout.CENTER);
        if (bIncludeNorthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createTableFindToolBar());
            if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.NORTH);
        }
        if (bIncludeSouthToolbar) {
            JToolBar toolBar = createToolBar(ToolBarOptions.createSouthTableToolBar());
            if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.SOUTH);
        }
        return pan;
    }
    public JPanel createReadOnlyTablePanel() {
        OATable table = createReadOnlyTable();
        // table.setSelectHub(getModel().getMultiSelectHub());
    
        OATableScrollPane tableScrollPane = createTableScrollPane(table);
        tableScrollPane.setBorder(new TitledBorder(""));
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(tableScrollPane, BorderLayout.CENTER);
        
        JToolBar toolBar = createToolBar(ToolBarOptions.createSouthTableToolBar());
        if (toolBar != null) pan.add(new OAScroller(toolBar), BorderLayout.SOUTH);
        
        return pan;
    }
    public JPanel createCombinedPanel() {
        return createCombinedPanel(false); 
    }
    protected boolean bHasCombinedPanel;
    public JPanel createCombinedPanel(final boolean bUseList) {
        bHasCombinedPanel = true;
        JTabbedPane tp;
        if (this.tabbedPane == null) tp = getTabbedPane();
        else tp = createTabbedPane();
        tp.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT);
        JSplitPane splitPane;
        final JComponent comp = createEditPanel(tp, false);
        Dimension d = new Dimension(5,5);
        comp.setMinimumSize(d);
        if (bUseList) {
            JPanel panel = new JPanel(new GridBagLayout());
            panel.setBorder(new EmptyBorder(2,2, 2,2));
            GridBagConstraints gc = new GridBagConstraints();
            gc.insets = new Insets(2, 2, 2, 2);
            gc.anchor = gc.WEST;
            gc.gridwidth = 1;
            gc.gridheight = 1;
            gc.fill = gc.NONE;
            
            JLabel lbl = new JLabel(Resource.getJarIcon("find16.png"));
            lbl.setText("Find: "); 
            OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), lbl);
            lbl.setToolTipText("Search using Package Name");
            panel.add(lbl, gc); 
            
            gc.gridwidth = gc.REMAINDER;
            gc.fill = gc.HORIZONTAL;
            panel.add(new OAResizePanel(createAutoCompleteTextField()), gc);
            gc.fill = gc.BOTH;
            gc.weightx = gc.weighty = 1.0;
            panel.add(new JScrollPane(createRecursiveTree()), gc);
            
            splitPane = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT,
                    panel, 
                    comp
            );
        }
        else {
            JComponent comp2 = createTableCardPanel(false, false);
            comp2.setMinimumSize(d);
            splitPane = new OASplitPane(JSplitPane.VERTICAL_SPLIT,
                    comp2, 
                    comp
            ) {
                @Override
                public void addNotify() {
                    super.addNotify();
                    Dimension d = getSize();
                    Dimension d2 = comp.getPreferredSize();
                    if (d2.height > d.height) {
                        setResizeWeight(.50);
                    }
                }
            };
        }
        
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        splitPane.setResizeWeight(bUseList ? .0 : .95);
        
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(splitPane, BorderLayout.CENTER);
        
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createTableToolBar())), BorderLayout.NORTH);
        return pan;
    }
    
    public JPanel createSplitPanel(int splitType, ToolBarOptions tbOptions, JComponent compTop, JComponent compBottom) {
        compBottom.setMinimumSize(new Dimension(5,5));
        JSplitPane splitPane = new OASplitPane(splitType, compTop, compBottom) {
            @Override
            public void addNotify() {
                super.addNotify();
                Dimension d = getSize();
                Dimension d2 = compBottom.getPreferredSize();
                if (splitType == JSplitPane.VERTICAL_SPLIT && d2.height > d.height) {
                    setResizeWeight(.25);
                }
                if (splitType == JSplitPane.VERTICAL_SPLIT && getLevel() > 1) setDividerLocation(9999);
            }
        };
        splitPane.setOneTouchExpandable(true);
        splitPane.setDividerSize(12);
        JPanel pan = new JPanel(new BorderLayout());
        pan.add(splitPane, BorderLayout.CENTER);
        if (tbOptions != null) pan.add(new OAScroller(createToolBar(tbOptions)), BorderLayout.NORTH);
        return pan;
    }
    
    public JPopupMenu createTablePopupMenu() {
        JPopupMenu pmenu = new JPopupMenu();
        OAMenuItem mi = createGotoEditMenuItem();
        if (mi != null) pmenu.add(mi);
    
        mi = createTableNewMenuItem();
        if (mi != null) {
            mi.setFocusComponent(tableDtTxtCreated);
            pmenu.add(mi);
        }
        mi = createInsertMenuItem();
        if (mi != null) {
            mi.setFocusComponent(tableDtTxtCreated);
            pmenu.add(mi);
        }
    
        mi = createSaveMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createRemoveMenuItem();
        if (mi != null) {
            pmenu.add(mi);
            pmenu.addSeparator();
        }
        mi = createDeleteMenuItem();
        if (mi != null) {
            pmenu.add(mi);
            pmenu.addSeparator();
        }
        mi = createCutMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createCopyMenuItem();
        if (mi != null) pmenu.add(mi);
        mi = createPasteMenuItem();
        if (mi != null) pmenu.add(mi);
        return pmenu;
    }
    
    public OAMenuItem createGotoEditMenuItem() {
        if (!getModel().getAllowGotoEdit()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), "Details ...", Resource.getJarIcon(Resource.IMG_Goto)) {
            @Override
            public boolean onActionPerformed() {
                PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                return true;
            }
        };
        mi.setMnemonic(KeyEvent.VK_G);
        return mi;
    }
    
    public OAMenuItem createTableNewMenuItem() {
        if (!getModel().getAllowNew()) return null;
        OAMenuItem mi = new OAMenuItem(getHub(), OAMenuItem.NEW);
        mi.setMnemonic(KeyEvent.VK_N);
        mi.setText("Create a new "+getModel().getDisplayName());
        mi.setFocusComponent(tableDtTxtCreated);
        return mi;
    }
    
    public OATableScrollPane createTableScrollPane(OATable table) {
        OATableScrollPane spTable = new OATableScrollPane(table, 1); // set number of fixed columns
        return spTable;
    }
    protected String getToolTipText(OATable table, int row, int col, String defaultValue) {
        // PackageInfo client = (PackageInfo) table.getHub().getAt(row);
        // defaultValue = PackageInfoDelegate.getToolTipText(client, true);
        return defaultValue;
    }
    public OATable createTable() {
        Hub<PackageInfo> hubTable;
        if (getModel().getAllowTableFilter()) hubTable = new Hub<PackageInfo>(PackageInfo.class);
        else hubTable = getModel().getHub();
     
        OATable table = new OATable(hubTable) {
            @Override
            public void customizeRenderer(JLabel lbl, Object value, boolean isSelected, boolean hasFocus, int row, int column, boolean wasChanged, boolean wasMouseOver) {
            }
            @Override
            public String getToolTipText(int row, int col, String defaultValue) {
                defaultValue = super.getToolTipText(row, col, defaultValue);
                return defaultValue;
            }
            @Override
            public void onDoubleClick() {
                if (PackageInfoJfcBase.this.getModel().getAllowGotoEdit()) {
                    PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                }
            }
        };
     
        // table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        if (hubTable != getModel().getHub()) {
            table.setMasterFilterHub(getModel().getHub());
        }
        table.setAllowDnD(true);
        table.setAllowSorting(getModel().getAllowTableSorting());
        // table.setColumnProperties(ModelDelegate.getProperties(), "PackageInfo");
    
        table.addCounterColumn();
        if (getModel().getAllowMultiSelect()) {
            table.addSelectionColumn(getModel().getMultiSelectHub(), "Select", 5);
        }
        createTableColumns(table);
        
        table.setPreferredSize(3, 2, true);
        table.setShowChanges(true);
        table.resizeColumnsToFitHeading();
        table.setComponentPopupMenu(createTablePopupMenu());
        return table;
    }
    
    public void createTableColumns(OATable table) {
        OALabel lbl;
        OATableColumn tc;
        tc = table.addColumn("Id", 6, createIdLabel());
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(PackageInfo.P_Id));
        }
        tableDtTxtCreated = createCreatedDateTimeTextField();
        tc = table.addColumn("Created", 15, tableDtTxtCreated);
        tc = table.addColumn("Package Name", 20, createPackageNameTextField());
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(PackageInfo.P_PackageName));
        }
    }
    
    public OATable createReadOnlyTable() {
        Hub<PackageInfo> hubTable;
        if (getModel().getAllowTableFilter()) hubTable = new Hub<PackageInfo>(PackageInfo.class);
        else hubTable = getModel().getHub();
        OATable table = new OATable(hubTable) {
            @Override
            public void customizeRenderer(JLabel lbl, JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column, boolean wasChanged, boolean wasMouseOver) {
            }
            @Override
            public String getToolTipText(int row, int col, String defaultValue) {
                defaultValue = super.getToolTipText(row, col, defaultValue);
                return defaultValue;
            }
            @Override
            public void onDoubleClick() {
                if (PackageInfoJfcBase.this.getModel().getAllowGotoEdit()) {
                    PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                }
            }
        };
     
        // table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table.setAllowDnD(false);
        table.setAllowSorting(getModel().getAllowTableSorting());
        if (getModel().getAllowTableFilter()) {
            table.setMasterFilterHub(getModel().getHub());
        }
        // table.setColumnProperties(ModelDelegate.getProperties(), "PackageInfo");
    
        table.addCounterColumn();
        if (getModel().getAllowMultiSelect()) {
            table.addSelectionColumn(getModel().getMultiSelectHub(), "Select", 6);
        }
        createReadOnlyTableColumns(table);
        
        table.resizeColumnsToFitHeading();
        table.setPreferredSize(3, 2, true);
        table.setComponentPopupMenu(createTablePopupMenu());
        return table;
    }
    
    protected void createReadOnlyTableColumns(OATable table) {
        OALabel lbl;
        OATableColumn tc;
        lbl = new OALabel(getHub(), PackageInfo.P_Id, 6);
        tc = table.addColumn("Id", 6, lbl);
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(PackageInfo.P_Id));
        }
        lbl = new OALabel(getHub(), PackageInfo.P_Created, 15);
        tc = table.addColumn("Created", 15, lbl);
        lbl = new OALabel(getHub(), PackageInfo.P_PackageName, 20);
        tc = table.addColumn("Package Name", 20, lbl);
        if (getModel().getAllowTableFilter()) {
            tc.setFilterComponent(new OATextFieldFilter(PackageInfo.P_PackageName));
        }
    }
    
    public OAButton createGotoEditButton() {
        if (!getModel().getAllowGotoEdit()) return null;
        OAButton cmd = new OAButton(getHub(), "Details ...", Resource.getJarIcon(Resource.IMG_Goto), OAButton.GOTO) {
            @Override
            public void afterActionPerformed() {
                PackageInfoJfcBase.this.getEditDialog(this).setVisible(true);
                super.afterActionPerformed();
            }
        };
        cmd.setToolTipText("go to the selected "+getModel().getDisplayName());
        OAButton.setup(cmd);
        return cmd;
    }
    
    public OAButton createAddButton() {
        if (!getModel().getAllowAdd()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.ADD_MANUAL) {
            @Override
            public boolean onActionPerformed() {
                PackageInfoJfcBase.this.onAdd();
                return true;
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Add ...");
        OAButton.setup(cmd);
        return cmd;
    }
    public OAButton createNewButton() {
        if (!getModel().getAllowNew()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.NEW) {
            public void afterActionPerformed() {
                PackageInfoJfcBase.this.onNewPackageInfoCreated();
                super.afterActionPerformed();
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("New");
        cmd.setup();
        cmd.setToolTipText("Create new "+getModel().getDisplayName());
        return cmd;
    }
    public OAButton createInsertButton() {
        if (!getModel().getAllowNew() || !getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.INSERT) {
            public void afterActionPerformed() {
                PackageInfoJfcBase.this.onNewPackageInfoCreated();
                super.afterActionPerformed();
            }
        };
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Insert");
        cmd.setup();
        cmd.setToolTipText("Insert a new "+getModel().getDisplayName());
        return cmd;
    }
    public OAButton createSaveButton() {
        if (!getModel().getAllowSave()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.SAVE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setText("Save");
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setup();
        cmd.setToolTipText("Save "+getModel().getDisplayName());
        return cmd;
    }
    
    public OAButton createRemoveButton() {
        if (!getModel().getAllowRemove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.REMOVE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setText("Remove");
        cmd.setup();
        cmd.setToolTipText("Remove "+getModel().getDisplayName()+" from this list");
        return cmd;
    }
    public OAButton createDeleteButton() {
        if (!getModel().getAllowDelete()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.DELETE);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        if (getModel().getAllowMultiSelect()) cmd.setMultiSelectHub(getModel().getMultiSelectHub());
        cmd.setConfirmMessage("OK to Delete this "+getModel().getDisplayName()+" from system?");
        cmd.setText("Delete ...");
        cmd.setup();
        cmd.setUseSwingWorker(true);
        cmd.setProcessingText("Processing ...", "Please wait while deleting "+getModel().getDisplayName());
        cmd.setToolTipText("Delete "+getModel().getDisplayName());
        return cmd;
    }
    
    public OAButton createMoveUpButton() {
        if (!getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.UP);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setup();
        cmd.setToolTipText("Move current "+getModel().getDisplayName()+" up in the list");
        return cmd;
    }
    public OAButton createMoveDownButton() {
        if (!getModel().getAllowMove()) return null;
        OAButton cmd = new OAButton(getHub(), OAButton.DOWN);
        cmd.getController().setViewOnly(getModel().getViewOnly());
        cmd.setup();
        cmd.setToolTipText("Move current "+getModel().getDisplayName()+" down in the list");
        return cmd;
    }
    
    public JToolBar createToolBar(final ToolBarOptions tbo) {
        JToolBar toolBar = new JToolBar();
        toolBar.setFloatable(false);
        toolBar.setRollover(true);
        toolBar.add(Box.createHorizontalStrut(10));
        updateToolBar(toolBar, tbo);
        toolBar.add(Box.createHorizontalGlue());
        return toolBar;
    }
    // main createToolBar
    public void updateToolBar(final JToolBar toolBar, final ToolBarOptions tbo) {
        JButton jcmd;
        OAButton cmd;
        
        if (tbo.bGoBack) {
            jcmd = createGotoListButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(7));
            }
        }
        if (tbo.bIcon) {
            Icon icon = getTitleIcon();
            JLabel lbl = new JLabel(getModel().getPluralDisplayName(), icon, JLabel.LEFT);
            lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
            toolBar.add(lbl);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bLabel) {
            OALabel lbl = new OALabel(getHub(), OAString.cpp(PackageInfo.P_PackageName));
            lbl.setToolTipTextPropertyPath(OAString.cpp(PackageInfo.P_PackageName));
            lbl.setMaxCols(20);
            lbl.setFont(lbl.getFont().deriveFont(Font.ITALIC));
            lbl.setBorder(new CustomLineBorder(0,0,0,1,Color.gray));
            toolBar.add(lbl);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bGoto) {
            cmd = createGotoEditButton();
            if (cmd != null) {
                toolBar.add(cmd);
                if (!tbo.bCommands) toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bCommands) {
            cmd = createMoveUpButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createMoveDownButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createSaveButton();
            if (cmd != null) toolBar.add(cmd);
            
            cmd = createAddButton();
            if (cmd != null) toolBar.add(cmd);
            
            cmd = createNewButton();
            if (cmd != null) {
                cmd.setFocusComponent(tableDtTxtCreated);
                toolBar.add(cmd);
            }
            cmd = createInsertButton();
            if (cmd != null) {
                cmd.setFocusComponent(tableDtTxtCreated);
                toolBar.add(cmd);
            }
            cmd = createRemoveButton();
            if (cmd != null) toolBar.add(cmd);
            cmd = createDeleteButton();
            if (cmd != null) toolBar.add(cmd);
            toolBar.add(Box.createHorizontalStrut(10));
        }
        if (tbo.bSearch) {
            jcmd = createSearchButton();
            if (jcmd == null) tbo.bSearch = false;
            else {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bFind) {
            OAAutoCompleteTextField txt = createAutoCompleteTextField();
            if (txt != null) {
                toolBar.add(Box.createHorizontalStrut(6));
                JLabel lbl = new JLabel(Resource.getJarIcon("find16.png"));
                lbl.setText("Find:");
                lbl.setToolTipText("Search using Package Name");
                OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), lbl);
                toolBar.add(lbl);
                toolBar.add(Box.createHorizontalStrut(5));
                toolBar.add(new OAResizePanel(txt));
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (!tbo.bSearch && tbo.bHubSearch) {
            jcmd = createHubSearchButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
        if (tbo.bCustom) {
            addCustomCommands(toolBar);
        }
        
        if (tbo.bDownload) {
            jcmd = createDownloadButton();
            if (jcmd != null) {
                toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
    
        if (tbo.bTable) {
            if (getModel().getAllowRecursive()) jcmd = createTableViewButton();
            else jcmd = null;
            if (jcmd != null) {
                toolBar.add(Box.createHorizontalStrut(5));
                JLabel lbl = new JLabel(Resource.getJarIcon("table16.png"));
                lbl.setText("Table:");
                OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), lbl);
                toolBar.add(lbl);
                toolBar.add(Box.createHorizontalStrut(5));
                if (jcmd != null) toolBar.add(jcmd);
                toolBar.add(Box.createHorizontalStrut(10));
            }
        }
    }
    public void addCustomCommands(JToolBar toolBar) {
        if (toolBar == null) return;
    }
    public JButton createGoBackButton() {
        return null;
    }
    public JButton createGotoListButton() {
        if (!getModel().getAllowGotoList()) return null;
        JButton cmd = new JButton();
        cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_GoBack)));
        cmd.setText("Listing");
        cmd.setToolTipText("Go to listing");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.showCardPanel(PackageInfoJfcBase.this.CARD_List);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public OAButton createSearchButton() {
        if (!getModel().getAllowSearch()) return null;
        OAButton cmd = new OAButton(getHub(), getModel().getDisplayName() + " search ...", Resource.getJarIcon("search.gif"), OAButton.SEARCH) {
            @Override
            public Object getSearchObject() {
                PackageInfo packageInfo = PackageInfoJfcBase.this.onSearch();
                return packageInfo;
            }
            @Override
            public void afterActionPerformed() {
                super.afterActionPerformed();
                OATree tree = getTreeUsed();
                if (tree != null) {
                    tree.setSelectedNode(getHub().getAO());
                }
                onShowEditPanel();
            }
        };
        return cmd;
    }
    
    public JButton createHubSearchButton() {
        if (!getModel().getAllowHubSearch()) return null;
        OAButton cmd = new OAButton(getHub(), "Search ...", Resource.getJarIcon("hubsearch16.png"), OAButton.HUBSEARCH) {
            @Override
            public void afterActionPerformed() {
                PackageInfoJfcBase.this.onHubSearch();
                super.afterActionPerformed();
            }
        };
        cmd.setToolTipText("table search");
        return cmd;
    }
    public JButton createDownloadButton() {
        if (!getModel().getAllowDownload()) return null;
        JButton cmd = new JButton("Download ...");
        cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_Download)));
        cmd.setToolTipText("download data to csv file");
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.onDownload();
            }
        });
        OAJfcController jc = OAJfcControllerFactory.createOnlyHubNotEmpty(getHub(), cmd);
        OAButton.setup(cmd);
        return cmd;
    }
    protected void onDownload() {
        DownloadDialog dd = new DownloadDialog<PackageInfo>(getHub());
        addDownloadProperties(dd);
        dd.download();
    }
    protected void addDownloadProperties(DownloadDialog dd) {
        dd.addProperty("Id", PackageInfo.P_Id);
        dd.addProperty("id", PackageInfo.P_Id);
        dd.addProperty("created", PackageInfo.P_Created);
        dd.addProperty("packageName", PackageInfo.P_PackageName);
    }
    // Card Panel
    public JPanel getCardPanel() {
        if (cardPanel != null) return cardPanel;
        cardLayout = new CardLayout(5,5) {
            JPanel panList;
            JPanel panEdit;
            @Override
            public void show(Container parent, String name) {
                if (CARD_List.equals(name)) {
                    if (panList == null) {
                        panList = createListCardPanel();
                        cardPanel.add(panList, CARD_List);
                    }
                }
                else if (CARD_Edit.equals(name)) {
                    if (panEdit == null) {
                        panEdit = createEditCardPanel();
                        cardPanel.add(panEdit, CARD_Edit);
                    }
                }
                super.show(parent, name);
            }
        };
        cardPanel = new JPanel(getCardLayout());
        
        cardPanel.add(new JLabel("loading ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), CARD_Edit);
        
        getCardLayout().show(cardPanel, CARD_List);
        return cardPanel;
    }
    public JPanel createListCardPanel() {
        JPanel pan = new JPanel(new BorderLayout());
        if (getModel().getAllowSearch()) {
            pan.add(createTableCardPanel(true, true), BorderLayout.CENTER);
        }
        else {
            pan.add(createTableCardPanel(false, true), BorderLayout.CENTER);
            pan.add(new OAScroller(createToolBar(ToolBarOptions.createMainTableToolBar())), BorderLayout.NORTH);
        }
        return pan;
    }
    public JPanel createEditCardPanel() {
        return createEditCardPanel(null);
    }
    public JPanel createEditCardPanel(JTabbedPane tp) {
        JPanel pan = new JPanel(new BorderLayout());
        if (tp == null) {
            if (this.tabbedPane == null) tp = getTabbedPane();
            else tp = createTabbedPane();
        }
        pan.add(createEditPanel(tp, true), BorderLayout.CENTER);
        pan.add(new OAScroller(createToolBar(ToolBarOptions.createEditPanelToolBar())), BorderLayout.NORTH);
        // cardPanel.add(getClassInfosJfc().getCardPanel(), CARD_ClassInfos); // this will be created when needed by showCardPanel(..)
        // cardPanel.add(getPackageInfosJfc().getCardPanel(), CARD_PackageInfos); // this will be created when needed by showCardPanel(..)
        return pan;
    }
    public CardLayout getCardLayout() {
        if (cardLayout == null) {
            cardLayout = new CardLayout(5,5);
        }
        return cardLayout;
    }
    
    // Edit Panel
    public JPanel createEditPanel() {
        return createEditPanel(null, true);
    }
    public JPanel createEditPanel(JTabbedPane tabbedPane, final boolean bUseCombinedDetail) {
        if (tabbedPane == null) {
            if (this.tabbedPane == null) tabbedPane = getTabbedPane();
            else tabbedPane = createTabbedPane();
        }
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(2, 2, 2, 2);
        gc.anchor = gc.WEST;
        JPanel panel;
        JLabel lbl;
        JToolBar toolBar;
        OALabel olbl;
        JButton cmd;
        JComponent comp;
        OAJfcController jfcController;
        OADateTimeTextField dttxt;
        OATextField txt;
        JPanel pan;
        JPanel panMain = new JPanel(new BorderLayout());
        panel = new JPanel(new GridBagLayout());
        panel.setBorder(new EmptyBorder(5,5, 3,3));
    
        lbl = new JLabel("Created:");
        gc.anchor = gc.WEST;
        panel.add(lbl, gc);
        gc.anchor = gc.NORTHWEST;
        dttxt = createCreatedDateTimeTextField();
        if (getModel().getViewOnly()) dttxt.getController().setViewOnly(true);
        dttxt.setLabel(lbl);
        dttxtCreated = dttxt;
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        comp = new OAResizePanel(dttxt, 95);
        panel.add(comp, gc);
        gc.fill = gc.NONE;
        gc.gridwidth = 1;
    
        lbl = new JLabel("Package Name:");
        gc.anchor = gc.WEST;
        panel.add(lbl, gc);
        gc.anchor = gc.NORTHWEST;
        txt = createPackageNameTextField();
        if (getModel().getViewOnly()) txt.getController().setViewOnly(true);
        txt.setLabel(lbl);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        comp = new OAResizePanel(txt, 95);
        panel.add(comp, gc);
        gc.fill = gc.NONE;
        gc.gridwidth = 1;
        if (getModel().getProjectInfoModel().getCreateUI()) {
            lbl = new JLabel("Project Info:");
            gc.anchor = gc.WEST;
            panel.add(lbl, gc);
            gc.anchor = gc.NORTHWEST;
            gc.gridwidth = gc.REMAINDER;
            gc.fill = gc.HORIZONTAL;
            olbl = createProjectInfoLabel();
            if (getModel().getViewOnly()) olbl.getController().setViewOnly(true);
            OAJfcControllerFactory.createOnlyAoNotNull(getHub(), lbl);
            cmd = createProjectInfoCommand();
            comp = olbl;
            comp = new OAResizePanel(comp, cmd);
            panel.add(comp, gc);
            gc.gridwidth = 1;
            gc.fill = gc.NONE;
        }
        if (getModel().getParentPackageInfoModel().getCreateUI()) {
            lbl = new JLabel("Parent Package Info:");
            gc.anchor = gc.WEST;
            panel.add(lbl, gc);
            gc.anchor = gc.NORTHWEST;
            gc.gridwidth = gc.REMAINDER;
            gc.fill = gc.HORIZONTAL;
            olbl = createParentPackageInfoLabel();
            if (getModel().getViewOnly()) olbl.getController().setViewOnly(true);
            OAJfcControllerFactory.createOnlyAoNotNull(getHub(), lbl);
            cmd = createParentPackageInfoCommand();
            comp = olbl;
            comp = new OAResizePanel(comp, cmd);
            panel.add(comp, gc);
            gc.gridwidth = 1;
            gc.fill = gc.NONE;
        }
        if (getModel().getPageModel().getCreateUI()) {
            lbl = new JLabel("Page:");
            gc.anchor = gc.WEST;
            panel.add(lbl, gc);
            gc.anchor = gc.NORTHWEST;
            gc.gridwidth = gc.REMAINDER;
            gc.fill = gc.HORIZONTAL;
            olbl = createPageLabel();
            if (getModel().getViewOnly()) olbl.getController().setViewOnly(true);
            OAJfcControllerFactory.createOnlyAoNotNull(getHub(), lbl);
            cmd = createPageCommand();
            comp = olbl;
            comp = new OAResizePanel(comp, cmd);
            panel.add(comp, gc);
            gc.gridwidth = 1;
            gc.fill = gc.NONE;
        }
    
        // take up remaining space
        lbl = new JLabel("");
        panel.add(lbl, gc);
        gc.gridwidth = gc.REMAINDER;
        gc.weightx = gc.weighty = 1.0f;
        gc.fill = gc.BOTH;
        panel.add(lbl, gc);
        gc.gridwidth = 1;
        gc.weightx = gc.weighty = 0.0f;
        gc.fill = gc.NONE;
    
        tabbedPane.addTab(getModel().getDisplayName(), getIcon(), new JScrollPane(panel), null);
        panMain.add(tabbedPane, BorderLayout.CENTER);
    
        Icon icon;
        icon = Resource.getJarIcon("classInfo.gif");
        icon = new ScaledImageIcon(icon, 32, 20);
        tabbedPane.addChangeListener(new ChangeListener() {
            volatile JPanel panThis;
            volatile Exception ex;
            @Override
            public void stateChanged(ChangeEvent e) {
                if (panThis != null) return;
                if (PackageInfoJfcBase.this.TAB_ClassInfos == 0) return;
                final JTabbedPane tp = (JTabbedPane) e.getSource();
                if (tp.getSelectedIndex() != PackageInfoJfcBase.this.TAB_ClassInfos) return;
                SwingWorker<Void, Void> sw = new SwingWorker<Void, Void>() {
                    @Override
                    protected Void doInBackground() throws Exception {
                        try {
                            if (bUseCombinedDetail) panThis = getClassInfosJfc().createCombinedPanel();
                            else panThis = getClassInfosJfc().createTablePanel();
                        }
                        catch (Exception e) {
                            ex = e;
                        }
                        return null;
                    }
                    @Override
                    protected void done() {
                        if (ex != null) {
                            LOG.log(Level.WARNING, "UI exception creating UI for PackageInfo", ex);
                            JOptionPane.showMessageDialog(null, "Exception while creating UI, message sent to tech support", "UI Exception", JOptionPane.ERROR_MESSAGE);
                        }
                        if (panThis == null) panThis = new JPanel();
                        tp.setComponentAt(PackageInfoJfcBase.this.TAB_ClassInfos, panThis);
                    }
                };
                sw.execute();
            }
        });
        if (getModel().getClassInfosModel().getCreateUI()) {
            if ((this.TAB_ClassInfos = tabbedPane.getTabCount()) == 0) {;
                JPanel panThis;
                if (bUseCombinedDetail) panThis = getClassInfosJfc().createCombinedPanel();
                else panThis = getClassInfosJfc().createTablePanel();
                tabbedPane.setComponentAt(PackageInfoJfcBase.this.TAB_ClassInfos, panThis);
            }
            else {
                tabbedPane.addTab("Class Infos", icon, new JLabel("loading ...", Resource.getJarIcon("wait.png"), JLabel.CENTER), "Class Infos");
            }
        }
        icon = Resource.getJarIcon("packageInfo.gif");
        icon = new ScaledImageIcon(icon, 32, 20);
        pan = getPackageInfosJfc().createReadOnlyTablePanel();
        if (getModel().getPackageInfosModel().getCreateUI()) {
            this.TAB_PackageInfos = tabbedPane.getTabCount();
            tabbedPane.addTab("Package Infos", icon, pan, null);
        }
        panel = panMain;
        return panel;
    }
    
    public JTabbedPane getTabbedPane() {
        if (tabbedPane == null) {
            tabbedPane = createTabbedPane();
        }
        return tabbedPane;
    }
    public JTabbedPane createTabbedPane() {
        JTabbedPane tabbedPane = new JTabbedPane();
        new TabbedPaneController(getHub(), tabbedPane);
        tabbedPane.setTabLayoutPolicy(JTabbedPane.SCROLL_TAB_LAYOUT); // WRAP_TAB_LAYOUT
        tabbedPane.setFocusable(true);
        return tabbedPane;
    }
    
    // edit dialog
    public JDialog getEditDialog(Component comp) {
        JDialog dlgEdit;
        if (wrEditDialog != null) {
            dlgEdit = wrEditDialog.get();
            if (dlgEdit != null) return dlgEdit;
        }
        if (jfcClassInfos != null) {
            // need to create a new Jfc for dialog
            PackageInfoJfc jfc = new PackageInfoJfc(getModel());
            dlgEdit = jfc.getEditDialog(comp);
            wrEditDialog = new WeakReference(dlgEdit);
            return dlgEdit;
        }
        Window win = JfcDelegate.getWindow(comp);
        if (win == null) win = OAJfcUtil.getMainWindow();
        final Hub<PackageInfo> hub = new Hub<PackageInfo>(PackageInfo.class);
        hub.setSharedHub(PackageInfoJfcBase.this.getModel().getHub(), true);
        dlgEdit = new JDialog(win, getModel().getDisplayName(), ModalityType.MODELESS) {
            @Override
            public void setVisible(boolean b) {
                super.setVisible(b);
                if (b) hub.setSharedHub(PackageInfoJfcBase.this.getModel().getHub(), true);
                else hub.setSharedHub(null);
            }
        };
        wrEditDialog = new WeakReference(dlgEdit);
        dlgEdit.setDefaultCloseOperation(JDialog.HIDE_ON_CLOSE);
        dlgEdit.setLayout(new BorderLayout());
        JToolBar tb = createToolBar(ToolBarOptions.createDialogToolBar());
        if (tb != null) {
            dlgEdit.add(new OAScroller(tb), BorderLayout.NORTH);
        }
        PackageInfoJfc jfc = new PackageInfoJfc(getModel());
        JPanel panEdit = jfc.createEditPanel();
        dlgEdit.add(panEdit, BorderLayout.CENTER);
        
        panEdit.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false), "esc");
        panEdit.getActionMap().put("esc", new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                getEditDialog(null).setVisible(false);
            }
        });
        
        OAJfcUtil.pack(dlgEdit);
        Dimension dimMax;
        if (win != null) {
            dimMax = win.getSize();
        }
        else {
            dimMax = Toolkit.getDefaultToolkit().getScreenSize();
        }
        Dimension dim = dlgEdit.getSize();
        dim.width *= 1.25;
        dim.height *= 1.25;
        dim.width = (int) Math.min(dim.width, dimMax.width);
        dim.height = (int) Math.min(dim.height, dimMax.height);
        dimMax.width *= .75;
        dimMax.height *= .75;
        dim.width = (int) Math.max(dim.width, dimMax.width);
        dim.height = (int) Math.max(dim.height, dimMax.height);
        dlgEdit.setSize(dim);
        
        if (win != null) dlgEdit.setLocationRelativeTo(win);
        return dlgEdit;
    }
    
    
    public OALabel createIdLabel() {
        OALabel lbl = new OALabel(getHub(), PackageInfo.P_Id, 6);
        lbl.setMaximumColumns(8);
        return lbl;
    }
    
    public OADateTimeTextField createCreatedDateTimeTextField() {
        OADateTimeTextField dttxt = new OADateTimeTextField(getHub(), PackageInfo.P_Created, 15);
        dttxt.setMinimumColumns(0);
        dttxt.setMaximumColumns(22);
        // setup(dttxt);
        return dttxt;
    }
    
    public OATextField createPackageNameTextField() {
        OATextField txt = new OATextField(getHub(), PackageInfo.P_PackageName, 20);
        txt.setMinimumColumns(0);
        txt.setMaximumColumns(75);
        // setup(txt);
        return txt;
    }
    
    public OALabel createSeqLabel() {
        OALabel lbl = new OALabel(getHub(), PackageInfo.P_Seq, 6);
        lbl.setMaximumColumns(8);
        return lbl;
    }
    
    public OALabel createPageLabel() {
        OALabel lbl = getPageJfc().createLabel();
        return lbl;
    }
    public JButton createPageCommand() {
        JButton cmd = null;
        cmd = getPageJfc().createGotoEditButton();
        return cmd;
    }
    
    public OALabel createParentPackageInfoLabel() {
        OALabel lbl = getParentPackageInfoJfc().createLabel();
        return lbl;
    }
    public JButton createParentPackageInfoCommand() {
        JButton cmd = null;
        OAMultiButtonSplitButton mscmd = new OAMultiButtonSplitButton();
        mscmd.setShowTextInSelectedButton(true);
        mscmd.setAllowChangeMasterButton(false);
        mscmd.setRequestFocusEnabled(false);
        mscmd.setFocusPainted(false);
        OAButton.setup(mscmd);
        cmd = getParentPackageInfoJfc().createGotoEditButton();
        if (cmd != null) {
            ((OAButton)cmd).getController().setViewOnly(getModel().getViewOnly());
            mscmd.addButton(cmd);
        }
        ((OAButton)cmd).getController().setViewOnly(getModel().getViewOnly());
        cmd = getParentPackageInfoJfc().createSearchButton();
        if (cmd != null) {
            ((OAButton)cmd).getController().setViewOnly(getModel().getViewOnly());
            cmd.setText("Search ...");
            mscmd.addButton(cmd);
        }
        boolean b = true;
        Hub h;
        if (b) {
            cmd = new OAButton(getModel().getParentPackageInfoHub(), OAButton.CLEARAO);
            cmd.setText("Clear");
            ((OAButton)cmd).getController().setViewOnly(getModel().getViewOnly());
            mscmd.addButton(cmd);
        }
        return mscmd;
    }
    
    public OALabel createProjectInfoLabel() {
        OALabel lbl = getProjectInfoJfc().createLabel();
        return lbl;
    }
    public JButton createProjectInfoCommand() {
        JButton cmd = null;
        cmd = getProjectInfoJfc().createSearchButton();
        if (cmd != null) {
        ((OAButton)cmd).getController().setViewOnly(getModel().getViewOnly());
            cmd.setText("Search ...");
        }
        return cmd;
    }
    
    protected void setup(JTextComponent txt) {
        OATextController tc = new OATextController(txt, Resource.getSpellChecker(), true);
        String s = txt.getToolTipText();
        if (!OAString.isEmpty(s)) s = "<html>"+s+"<br>";
        else s = "<html>";
        s += "<small><i>Right click for more options";
        txt.setToolTipText(s);
    }
    
    // Autocomplete
    public OAAutoCompleteTextField createAutoCompleteTextField() {
        return createAutoCompleteTextField(PP_Display);
    }
    public OAAutoCompleteTextField createAutoCompleteTextField(String propertyPath) {
        OAAutoCompleteTextField txt = new OAAutoCompleteTextField(getHub(), propertyPath, 20);
        txt.setMaximumColumns(75);
        txt.setToolTipText("Search using Package Name");
        return txt;
    }
    
    
    public PageJfc getPageJfc() {
        if (jfcPage != null) return jfcPage;
        jfcPage = new PageJfc(getModel().getPageModel()) {
        };
        jfcPage.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcPage, this);
        return jfcPage;
    }
    public PackageInfoJfc getParentPackageInfoJfc() {
        if (jfcParentPackageInfo != null) return jfcParentPackageInfo;
        jfcParentPackageInfo = new PackageInfoJfc(getModel().getParentPackageInfoModel()) {
            @Override
            protected PackageInfoSearchJfc getSearchJfc() {
                if (jfcSearch != null) return jfcSearch;
                PackageInfoJfcBase.this.getModel().getParentPackageInfoSearchModel().getPackageInfoSearch().setMaxResults(1000);
                jfcSearch = new PackageInfoSearchJfc(PackageInfoJfcBase.this.getModel().getParentPackageInfoSearchModel());
                return jfcSearch;
            }
            @Override
            protected PackageInfo onSearch() {
                getSearchJfc().getDialog().setVisible(true);
                if (!getSearchJfc().wasSelected()) return null;
                
                PackageInfo packageInfo = getSearchJfc().getSelected();
                return packageInfo;
            }
        };
        jfcParentPackageInfo.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcParentPackageInfo, this);
        return jfcParentPackageInfo;
    }
    public ProjectInfoJfc getProjectInfoJfc() {
        if (jfcProjectInfo != null) return jfcProjectInfo;
        jfcProjectInfo = new ProjectInfoJfc(getModel().getProjectInfoSelectFromModel()) {
            @Override
            protected ProjectInfoSearchJfc getSearchJfc() {
                if (jfcSearch != null) return jfcSearch;
                PackageInfoJfcBase.this.getModel().getProjectInfoSearchModel().getProjectInfoSearch().setMaxResults(1000);
                jfcSearch = new ProjectInfoSearchJfc(PackageInfoJfcBase.this.getModel().getProjectInfoSearchModel());
                return jfcSearch;
            }
        };
        jfcProjectInfo.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcProjectInfo, this);
        return jfcProjectInfo;
    }
    public ClassInfoJfc getClassInfosJfc() {
        if (jfcClassInfos == null) {
            jfcClassInfos = createClassInfosJfc();
        }
        return jfcClassInfos;
    }
    public ClassInfoJfc createClassInfosJfc() {
        jfcClassInfos = new ClassInfoJfc(getModel().getClassInfosModel()) {
            @Override
            public JPanel getCardPanel() {
                if (cardPanel != null) return cardPanel;
                cardPanel = new JPanel(getCardLayout());
                JPanel pan = new JPanel(new BorderLayout());
                pan.add(createToolBar(ToolBarOptions.createEditPanelToolBar()), BorderLayout.NORTH);
                pan.add(createEditPanel(), BorderLayout.CENTER);
                cardPanel.add(pan, CARD_Edit);
                return cardPanel;
            }
    
            @Override
            public void showCardPanel(String name) {
                if (name.equals(ClassInfoJfc.CARD_List)) {
                    PackageInfoJfcBase.this.showCardPanel(CARD_Edit);
                    if (PackageInfoJfcBase.this.TAB_ClassInfos >= 0) {
                        PackageInfoJfcBase.this.getTabbedPane().setSelectedIndex(PackageInfoJfcBase.this.TAB_ClassInfos);
                    }
                }
                else if (name.equals(ClassInfoJfcBase.CARD_Edit)) {
                    PackageInfoJfcBase.this.showCardPanel(CARD_Edit);
                    if (PackageInfoJfcBase.this.TAB_ClassInfos >= 0) {
                        PackageInfoJfcBase.this.getTabbedPane().setSelectedIndex(PackageInfoJfcBase.this.TAB_ClassInfos);
                    }
                }
                else {
                    PackageInfoJfcBase.this.showCardPanel(CARD_ClassInfos);
                    super.showCardPanel(name);
                }
            }
            public JButton createGoBackButton() {
                JButton cmd = new JButton();
                cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_GoBack)));
                cmd.setToolTipText("Go to " + PackageInfoJfcBase.this.getModel().getDisplayName());
                cmd.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        PackageInfoJfcBase.this.showCardPanel(PackageInfoJfcBase.this.CARD_Edit);
                        PackageInfoJfcBase.this.getHub().resetAO(); // this will set selected treeNode
                    }
                });
                OAButton.setup(cmd);
                return cmd;
            }
        };
        jfcClassInfos.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcClassInfos, this);
        return jfcClassInfos;
    }
    public PackageInfoJfc getPackageInfosJfc() {
        if (jfcPackageInfos == null) {
            jfcPackageInfos = createPackageInfosJfc();
        }
        return jfcPackageInfos;
    }
    public PackageInfoJfc createPackageInfosJfc() {
        jfcPackageInfos = new PackageInfoJfc(getModel().getPackageInfosModel()) {
            @Override
            protected PackageInfoSearchJfc getSearchJfc() {
                if (jfcSearch != null) return jfcSearch;
                PackageInfoSearchModel model = PackageInfoJfcBase.this.getModel().getPackageInfosSearchModel();
                jfcSearch = new PackageInfoSearchJfc(model, true, false);
                return jfcSearch;
            }
            @Override
            public JPanel getCardPanel() {
                if (cardPanel != null) return cardPanel;
                cardPanel = new JPanel(getCardLayout());
                JPanel pan = new JPanel(new BorderLayout());
                pan.add(createToolBar(ToolBarOptions.createEditPanelToolBar()), BorderLayout.NORTH);
                pan.add(createEditPanel(), BorderLayout.CENTER);
                cardPanel.add(pan, CARD_Edit);
                return cardPanel;
            }
    
            @Override
            public void showCardPanel(String name) {
                if (name.equals(PackageInfoJfc.CARD_List)) {
                    PackageInfoJfcBase.this.showCardPanel(CARD_Edit);
                    if (PackageInfoJfcBase.this.TAB_PackageInfos >= 0) {
                        PackageInfoJfcBase.this.getTabbedPane().setSelectedIndex(PackageInfoJfcBase.this.TAB_PackageInfos);
                    }
                }
                else if (name.equals(PackageInfoJfcBase.CARD_Edit)) {
                    PackageInfoJfcBase.this.showCardPanel(CARD_Edit);
                    if (PackageInfoJfcBase.this.TAB_PackageInfos >= 0) {
                        PackageInfoJfcBase.this.getTabbedPane().setSelectedIndex(PackageInfoJfcBase.this.TAB_PackageInfos);
                    }
                }
                else {
                    PackageInfoJfcBase.this.showCardPanel(CARD_PackageInfos);
                    super.showCardPanel(name);
                }
            }
            public JButton createGoBackButton() {
                JButton cmd = new JButton();
                cmd.setIcon(Resource.getJarIcon(Resource.getValue(Resource.IMG_GoBack)));
                cmd.setToolTipText("Go to " + PackageInfoJfcBase.this.getModel().getDisplayName());
                cmd.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        PackageInfoJfcBase.this.showCardPanel(PackageInfoJfcBase.this.CARD_Edit);
                        PackageInfoJfcBase.this.getHub().resetAO(); // this will set selected treeNode
                    }
                });
                OAButton.setup(cmd);
                return cmd;
            }
        };
        getModel().getPackageInfosModel().setType(PackageInfoModel.TYPE_TreeTable);
        jfcPackageInfos.setLevel(getLevel()+1);
        OAModelJfcUtil.setParent(jfcPackageInfos, this);
        return jfcPackageInfos;
    }
    // OnShowCommands
    public void showCardPanel(String name) {
        if (name == null) return;
        if (cardPanel == null) return;
        if (name.equalsIgnoreCase(CARD_ClassInfos)) {
            if ( !OAArray.contains(cardPanel.getComponents(), getClassInfosJfc().getCardPanel()) ) {
                cardPanel.add(getClassInfosJfc().getCardPanel(), CARD_ClassInfos);
            }
        }
        else if (name.equalsIgnoreCase(CARD_PackageInfos)) {
            if ( !OAArray.contains(cardPanel.getComponents(), getPackageInfosJfc().getCardPanel()) ) {
                cardPanel.add(getPackageInfosJfc().getCardPanel(), CARD_PackageInfos);
            }
        }
        getCardLayout().show(getCardPanel(), name);
    }
    protected void onShowListPanel() {
        showCardPanel(CARD_List);
    }
    protected void onShowEditPanel() {
        showCardPanel(CARD_Edit);
    }
    protected void onNewPackageInfoCreated() {
        onShowEditPanel();
        if (getTabbedPane().getTabCount() > 0) {
            getTabbedPane().setSelectedIndex(0);
        }
    }
    protected void onDoubleClickTreeNode() {
        if (getModel().getAllowGotoEdit()) {
            getEditDialog(null).setVisible(true);
        }
    }
    
    // Inner Search
    public PackageInfoSearchJfc getSearchHubJfc() {
        if (jfcSearchHub != null) return jfcSearchHub;
        PackageInfoSearchModel modelSearch = new PackageInfoSearchModel();
        modelSearch.setSearchFromHub(getHub());
        jfcSearchHub = new PackageInfoSearchJfc(modelSearch, true, getModel().getAllowMultiSelect()) {
            @Override
            public JPanel createSearchFromPanel() {
                return null;
            }
            @Override
            public JPanel createSearchTreePanel() {
                return null;
            }
        };
        return jfcSearchHub;
    }
    protected void onHubSearch() {
        getSearchHubJfc().getDialog().setVisible(true);
        if (!getSearchHubJfc().wasSelected()) return;
        if (getModel().getAllowMultiSelect()) {
            getModel().getMultiSelectHub().clear();
            for (PackageInfo packageInfo : getSearchHubJfc().getModel().getMultiSelectHub()) {
                if (getHub().contains(packageInfo)) {
                    getModel().getMultiSelectHub().add(packageInfo);
                }
            }
            getHub().setAO(getModel().getMultiSelectHub().getAt(0));
        }
        else {
            PackageInfo packageInfo = getSearchHubJfc().getSelected();
            if (packageInfo != null) {
                if (getHub().contains(packageInfo)) {
                    getHub().setAO(packageInfo);
                }
            }
        }
    }
    // Search
    protected PackageInfoSearchJfc getSearchJfc() {
        if (jfcSearch == null) {
            jfcSearch = new PackageInfoSearchJfc();
        }
        return jfcSearch;
    }
    protected PackageInfo onSearch() {
        getSearchJfc().getModel().beforeInput();
        getSearchJfc().getDialog().setVisible(true);
        PackageInfo packageInfo = null;
        if (getSearchJfc().wasSelected()) packageInfo = getSearchJfc().getSelected();
        return packageInfo;
    }
    // Add
    protected PackageInfoSearchJfc getAddJfc() {
        if (jfcAdd == null) {
            jfcAdd = new PackageInfoSearchJfc();
        }
        return jfcAdd;
    }
    protected void onAdd() {
        getAddJfc().getDialog().setVisible(true);
        if (!getAddJfc().wasSelected()) return;
        PackageInfo packageInfo = getAddJfc().getSelected();
        if (packageInfo == null) return;
        getHub().add(packageInfo);
        getHub().setAO(packageInfo);
    }
    
    public OAMultiButtonSplitButton createTableViewButton() {
        final OAMultiButtonSplitButton mscmd = new OAMultiButtonSplitButton();
        mscmd.setShowTextInSelectedButton(true);
        mscmd.setAllowChangeMasterButton(true);
        mscmd.setRequestFocusEnabled(false);
        mscmd.setFocusPainted(false);
        OAButton.setup(mscmd);
        
        JButton cmd;
        getModel().addTypeListener(new HubListenerAdapter<VInteger>() {
            @Override
            public void afterPropertyChange(HubEvent<VInteger> e) {
                mscmd.setSelected(getModel().getType());
            }
        });
        cmd = createOriginalTableButton();
        mscmd.addButton(cmd);
        if (getModel().getAllowRecursive()) {
            cmd = createTreeTableButton();
            mscmd.addButton(cmd);
            cmd = createRootTableButton();
            mscmd.addButton(cmd);
            cmd = createFlattenedTableButton();
            mscmd.addButton(cmd);
            // cmd = createRecursiveTableButton();  // rarely used
            // mscmd.addButton(cmd);
        }
        mscmd.setBorderPainted(true);
        OAJfcControllerFactory.createOnlyHubValid(getModel().getOriginalHub(), mscmd);
        mscmd.setSelected(getModel().getType());
        return mscmd;
    }
    
    
    public JButton createOriginalTableButton() {
        JButton cmd = new JButton("Original list");
        cmd.setIcon(Resource.getJarIcon("list16.png"));
        cmd.setToolTipText("show the original list"); 
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_Original);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public JButton createRootTableButton() {
        JButton cmd = new JButton("Root list");
        cmd.setIcon(Resource.getJarIcon("list16.png"));
        cmd.setToolTipText("show only top level of the hierarchy list"); 
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_Root);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public JButton createTreeTableButton() {
        JButton cmd = new JButton("Hierarchy list");
        cmd.setIcon(Resource.getJarIcon("tree16.png"));
        cmd.setToolTipText("show data in hierarchy tree list"); 
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_TreeTable);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public JButton createFlattenedTableButton() {
        JButton cmd = new JButton("Flattened list");
        cmd.setIcon(Resource.getJarIcon("list16.png"));
        cmd.setToolTipText("show data in a flattened list, instead of a tree"); 
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_Flattened);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public JButton createRecursiveTableButton() {
        JButton cmd = new JButton("Selected node from tree");
        cmd.setIcon(Resource.getJarIcon("tree16.png"));
        cmd.setToolTipText("show selected node from the tree"); 
        cmd.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                PackageInfoJfcBase.this.getModel().setType(PackageInfoModel.TYPE_Recursive);
            }
        });
        OAButton.setup(cmd);
        return cmd;
    }
    
    public static void main(String[] args) {
        AppUser user = new AppUser();
        user.setAdmin(true);
        user.setEditProcessed(true);
        AppUserLogin userLogin = new AppUserLogin();
        userLogin.setAppUser(user);
        ModelDelegate.setLocalAppUserLogin(userLogin);
        TestDelegate td = new TestDelegate();
        td.createSampleData(null);
        
        com.viaoa.context.OAContext.setContextHub(null, ModelDelegate.getLocalAppUserHub());
        PackageInfoJfc ui = new PackageInfoJfc() {
            @Override
            protected PackageInfoSearchJfc getSearchJfc() {
                if (this.jfcSearch == null) {
                    this.jfcSearch = new PackageInfoSearchJfc(false) {
                        @Override
                        protected void onSearch(JComponent comp) {
                            super.onSearch(comp);
                            afterSearchCustom();
                        }
                    };
                }
                return this.jfcSearch;
            }
            private void afterSearchCustom() {
                getModel().getOriginalHub().setSharedHub(getSearchJfc().getModel().getHub());
            }
        };
        ui.getModel().setAllowNew(true);
        ui.getModel().setAllowDelete(true);
        
        JFrame frm = new JFrame();
        JfcDelegate.setMainWindow(frm);
        frm.setTitle(ui.getModel().getDisplayName());
        frm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JMenuBar menuBar = new JMenuBar();
        JMenu menu = new JMenu(ui.getModel().getPluralDisplayName());
        menu.add(ui.createNewMenuItem());
        menu.add(ui.createSaveMenuItem());
        menu.addSeparator();
        menu.add(ui.createDeleteMenuItem());
        menuBar.add(menu);
        
        frm.setJMenuBar(menuBar);
        
        OATree tree = new OATree(15, 17);
        tree.setAllowDnD(true);
        
        OATreeNode tn = ui.getTreeTitleNode();
        tree.add(tn);
        tn.add(ui.getTreeNode());
        
        String cmd = "esc";
        tree.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0 ,false), cmd);
        tree.getActionMap().put(cmd, new AbstractAction() {
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });
        
        frm.setLayout(new BorderLayout());
        
        // ui.getTablePanel().add(new OAScroller(ui.createToolBar(true)), BorderLayout.NORTH);
        // frm.add(ui.getTablePanel(), BorderLayout.SOUTH);
        
        JPanel pan = new JPanel(new BorderLayout());
        // pan.add(ui.createTitlePanel(), BorderLayout.NORTH);
        pan.add(ui.getCardPanel());
        
        JToolBar toolBar = ui.createToolBar(ToolBarOptions.createNorthTableSearchToolBar());
        if (toolBar != null) frm.add(new OAScroller(toolBar), BorderLayout.NORTH);
        
        toolBar = new JToolBar();
        toolBar.add(Box.createHorizontalStrut(25));
        AppUserJfc jfcAU = new AppUserJfc(ModelDelegate.getLocalAppUserHub());
        OACheckBox chk = jfcAU.createEditProcessedCheckBox();
        chk.setText("Edit Processed");
        toolBar.add(chk);
        chk = jfcAU.createAdminCheckBox();
        chk.setText("Is Admin");
        toolBar.add(chk);
        JPanel panx = new JPanel(new BorderLayout());
        panx.add(toolBar, BorderLayout.NORTH);
        
        JTabbedPane tabbedPane = new JTabbedPane();
        tabbedPane.add("Main", pan);
        
        pan = new JPanel(new GridBagLayout());
        pan.setBorder(new EmptyBorder(20,20,10,10));
        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(2, 2, 2, 2);
        gc.anchor = gc.WEST;
        pan.add(new JLabel("Label: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        pan.add(new OAResizePanel(ui.createLabel(), 75), gc);
        gc.gridwidth = 1;
        gc.fill = gc.NONE;
        pan.add(new JLabel("Combo: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.HORIZONTAL;
        pan.add(new OAResizePanel(ui.createComboBox(), 75), gc);
        gc.fill = gc.NONE;
        pan.add(new JLabel("List: "), gc);
        gc.gridwidth = gc.REMAINDER;
        gc.fill = gc.BOTH;
        gc.weightx = gc.weighty = 1.0;
        pan.add(new OAResizePanel(new JScrollPane(ui.createList()), 75, true), gc);
        pan.add(new JLabel(), gc);
        panx.add(new JScrollPane(pan), BorderLayout.CENTER);
        tabbedPane.add("Sample", panx);
        JSplitPane sp = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, new JScrollPane(tree), tabbedPane);
        sp.setOneTouchExpandable(true);
        sp.setDividerSize(6);
    
        /*
        sp = new OASplitPane(JSplitPane.HORIZONTAL_SPLIT, sp, new JScrollPane(ui.createList()));
        sp.setOneTouchExpandable(true);
        sp.setDividerSize(6);
        sp.setResizeWeight(.90);
        */
        frm.add(sp, BorderLayout.CENTER);
        
        OAJfcUtil.pack(frm);;
        Dimension d = frm.getSize();
        Dimension dimScreen = Toolkit.getDefaultToolkit().getScreenSize();
        d.width = Math.min(d.width, dimScreen.width - 80);
        d.height = Math.min(d.height, dimScreen.height - 80);
        frm.setSize(d);
        
        frm.setLocation(new Point(40, 40));
        frm.setVisible(true);
    }
}

