// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.search;

import javax.xml.bind.annotation.*;
import java.util.logging.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
@XmlRootElement(name = "classInfoSearch")
@XmlType(factoryMethod = "jaxbCreate")
@XmlAccessorType(XmlAccessType.PROPERTY)
public class ClassInfoSearch extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(ClassInfoSearch.class.getName());
    public static final String P_MaxResults = "MaxResults";

    protected int maxResults;

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public static ClassInfoSearch jaxbCreate() {
        ClassInfoSearch classInfoSearch = (ClassInfoSearch) OAObject.jaxbCreateInstance(ClassInfoSearch.class);
        if (classInfoSearch == null) classInfoSearch = new ClassInfoSearch();
        return classInfoSearch;
    }

    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<ClassInfo> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<ClassInfo> f = new OAQueryFilter<ClassInfo>(ClassInfo.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<ClassInfo> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<ClassInfo> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<ClassInfo> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<ClassInfo> select = new OASelect<ClassInfo>(ClassInfo.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        select.add(sql, args);
    }

    private OAFilter<ClassInfo> filterDataSourceFilter;
    public OAFilter<ClassInfo> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<ClassInfo>() {
            @Override
            public boolean isUsed(ClassInfo classInfo) {
                return ClassInfoSearch.this.isUsedForDataSourceFilter(classInfo);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<ClassInfo> filterCustomFilter;
    public OAFilter<ClassInfo> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<ClassInfo>() {
            @Override
            public boolean isUsed(ClassInfo classInfo) {
                boolean b = ClassInfoSearch.this.isUsedForCustomFilter(classInfo);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(ClassInfo searchClassInfo) {
        return true;
    }
    public boolean isUsedForCustomFilter(ClassInfo searchClassInfo) {
        return true;
    }
}
