// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.search;

import javax.xml.bind.annotation.*;
import java.util.logging.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
@XmlRootElement(name = "linkInfoSearch")
@XmlType(factoryMethod = "jaxbCreate")
@XmlAccessorType(XmlAccessType.PROPERTY)
public class LinkInfoSearch extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(LinkInfoSearch.class.getName());
    public static final String P_MaxResults = "MaxResults";

    protected int maxResults;

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public static LinkInfoSearch jaxbCreate() {
        LinkInfoSearch linkInfoSearch = (LinkInfoSearch) OAObject.jaxbCreateInstance(LinkInfoSearch.class);
        if (linkInfoSearch == null) linkInfoSearch = new LinkInfoSearch();
        return linkInfoSearch;
    }

    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<LinkInfo> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<LinkInfo> f = new OAQueryFilter<LinkInfo>(LinkInfo.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<LinkInfo> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<LinkInfo> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<LinkInfo> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<LinkInfo> select = new OASelect<LinkInfo>(LinkInfo.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        select.add(sql, args);
    }

    private OAFilter<LinkInfo> filterDataSourceFilter;
    public OAFilter<LinkInfo> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<LinkInfo>() {
            @Override
            public boolean isUsed(LinkInfo linkInfo) {
                return LinkInfoSearch.this.isUsedForDataSourceFilter(linkInfo);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<LinkInfo> filterCustomFilter;
    public OAFilter<LinkInfo> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<LinkInfo>() {
            @Override
            public boolean isUsed(LinkInfo linkInfo) {
                boolean b = LinkInfoSearch.this.isUsedForCustomFilter(linkInfo);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(LinkInfo searchLinkInfo) {
        return true;
    }
    public boolean isUsedForCustomFilter(LinkInfo searchLinkInfo) {
        return true;
    }
}
