// Generated by OABuilder
package com.viaoa.docbuilder.model.oa.search;

import javax.xml.bind.annotation.*;
import java.util.logging.*;
import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.annotation.*;
import com.viaoa.object.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.datasource.*;
import com.viaoa.filter.*;

@OAClass(useDataSource=false, localOnly=true)
@XmlRootElement(name = "packageInfoSearch")
@XmlType(factoryMethod = "jaxbCreate")
@XmlAccessorType(XmlAccessType.PROPERTY)
public class PackageInfoSearch extends OAObject {
    private static final long serialVersionUID = 1L;
    private static Logger LOG = Logger.getLogger(PackageInfoSearch.class.getName());
    public static final String P_MaxResults = "MaxResults";

    protected int maxResults;

    public int getMaxResults() {
        return maxResults;
    }
    public void setMaxResults(int newValue) {
        fireBeforePropertyChange(P_MaxResults, this.maxResults, newValue);
        int old = maxResults;
        this.maxResults = newValue;
        firePropertyChange(P_MaxResults, old, this.maxResults);
    }

    public static PackageInfoSearch jaxbCreate() {
        PackageInfoSearch packageInfoSearch = (PackageInfoSearch) OAObject.jaxbCreateInstance(PackageInfoSearch.class);
        if (packageInfoSearch == null) packageInfoSearch = new PackageInfoSearch();
        return packageInfoSearch;
    }

    public void reset() {
    }

    public boolean isDataEntered() {
        return false;
    }

    protected String extraWhere;
    protected Object[] extraWhereParams;
    protected OAFilter<PackageInfo> filterExtraWhere;

    public void setExtraWhere(String s, Object ... args) {
        this.extraWhere = s;
        this.extraWhereParams = args;
        if (OAString.isNotEmpty(s) && getExtraWhereFilter() == null) {
            OAFilter<PackageInfo> f = new OAQueryFilter<PackageInfo>(PackageInfo.class, s, args);
            setExtraWhereFilter(f);
        }
    }
    public void setExtraWhereFilter(OAFilter<PackageInfo> filter) {
        this.filterExtraWhere = filter;
    }
    public OAFilter<PackageInfo> getExtraWhereFilter() {
        return this.filterExtraWhere;
    }

    public OASelect<PackageInfo> getSelect() {
        final String prefix = "";
        String sql = "";
        String sortOrder = null;
        Object[] args = new Object[0];

        if (OAString.isNotEmpty(extraWhere)) {
            if (sql.length() > 0) sql = "(" + sql + ") AND ";
            sql += extraWhere;
            args = OAArray.add(Object.class, args, extraWhereParams);
        }

        OASelect<PackageInfo> select = new OASelect<PackageInfo>(PackageInfo.class, sql, args, sortOrder);
        if (getExtraWhereFilter() != null && getExtraWhereFilter().updateSelect(select)) {
            select.setFilter(new OAAndFilter(this.getCustomFilter(), getExtraWhereFilter()));
        }
        else select.setFilter(this.getCustomFilter());
        select.setDataSourceFilter(this.getDataSourceFilter());
        if (getMaxResults() > 0) select.setMax(getMaxResults());
        return select;
    }

    public void appendSelect(final String fromName, final OASelect select) {
        final String prefix = fromName + ".";
        String sql = "";
        Object[] args = new Object[0];
        select.add(sql, args);
    }

    private OAFilter<PackageInfo> filterDataSourceFilter;
    public OAFilter<PackageInfo> getDataSourceFilter() {
        if (filterDataSourceFilter != null) return filterDataSourceFilter;
        filterDataSourceFilter = new OAFilter<PackageInfo>() {
            @Override
            public boolean isUsed(PackageInfo packageInfo) {
                return PackageInfoSearch.this.isUsedForDataSourceFilter(packageInfo);
            }
        };
        return filterDataSourceFilter;
    }
    
    private OAFilter<PackageInfo> filterCustomFilter;
    public OAFilter<PackageInfo> getCustomFilter() {
        if (filterCustomFilter != null) return filterCustomFilter;
        filterCustomFilter = new OAFilter<PackageInfo>() {
            @Override
            public boolean isUsed(PackageInfo packageInfo) {
                boolean b = PackageInfoSearch.this.isUsedForCustomFilter(packageInfo);
                return b;
            }
        };
        return filterCustomFilter;
    }
    
    public boolean isUsedForDataSourceFilter(PackageInfo searchPackageInfo) {
        return true;
    }
    public boolean isUsedForCustomFilter(PackageInfo searchPackageInfo) {
        return true;
    }
}
