// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.application;

import java.util.logging.*;

public class ApplicationBar extends ApplicationBarBase {
    private static Logger LOG = Logger.getLogger(ApplicationBarBase.class.getName());
}
