// Generated by OABuilder 
package com.viaoa.docbuilder.view.client.panel.application;

import java.util.logging.Logger;

public class ApplicationPanel extends ApplicationPanelBase {
    private static Logger LOG = Logger.getLogger(ApplicationPanel.class.getName());
}
