// Generated by OABuilder

package com.viaoa.docbuilder.model;

import java.util.logging.*;
import com.viaoa.object.*;
import com.viaoa.annotation.*;
import com.viaoa.hub.*;
import com.viaoa.util.*;
import com.viaoa.filter.*;
import com.viaoa.datasource.*;

import com.viaoa.docbuilder.model.oa.*;
import com.viaoa.docbuilder.model.oa.propertypath.*;
import com.viaoa.docbuilder.model.oa.search.*;
import com.viaoa.docbuilder.model.oa.filter.*;
import com.viaoa.docbuilder.model.search.*;
import com.viaoa.docbuilder.model.filter.*;
import com.viaoa.docbuilder.delegate.ModelDelegate;
import com.viaoa.docbuilder.resource.Resource;

public class LinkInfoModel extends OAObjectModel {
    private static Logger LOG = Logger.getLogger(LinkInfoModel.class.getName());
    
    // Hubs
    protected Hub<LinkInfo> hub;
    // selected linkInfos
    protected Hub<LinkInfo> hubMultiSelect;
    // detail hubs
    protected Hub<Page> hubPage;
    
    // ObjectModels
    protected PageModel modelPage;
    
    // SearchModels used for references
    protected PageSearchModel modelPageSearch;
    
    public LinkInfoModel() {
        setDisplayName("Link Info");
        setPluralDisplayName("Link Infos");
    }
    
    public LinkInfoModel(Hub<LinkInfo> hubLinkInfo) {
        this();
        if (hubLinkInfo != null) HubDelegate.setObjectClass(hubLinkInfo, LinkInfo.class);
        this.hub = hubLinkInfo;
    }
    public LinkInfoModel(LinkInfo linkInfo) {
        this();
        getHub().add(linkInfo);
        getHub().setPos(0);
    }
    
    public Hub<LinkInfo> getOriginalHub() {
        return getHub();
    }
    
    public Hub<Page> getPageHub() {
        if (hubPage != null) return hubPage;
        hubPage = getHub().getDetailHub(LinkInfo.P_Page);
        return hubPage;
    }
    public LinkInfo getLinkInfo() {
        return getHub().getAO();
    }
    
    public Hub<LinkInfo> getHub() {
        if (hub == null) {
            hub = new Hub<LinkInfo>(LinkInfo.class);
        }
        return hub;
    }
    
    public Hub<LinkInfo> getMultiSelectHub() {
        if (hubMultiSelect == null) {
            hubMultiSelect = new Hub<LinkInfo>(LinkInfo.class);
        }
        return hubMultiSelect;
    }
    
    public PageModel getPageModel() {
        if (modelPage != null) return modelPage;
        modelPage = new PageModel(getPageHub());
        modelPage.setDisplayName("Page");
        modelPage.setPluralDisplayName("Pages");
        modelPage.setForJfc(getForJfc());
        modelPage.setAllowNew(true);
        modelPage.setAllowSave(true);
        modelPage.setAllowAdd(false);
        modelPage.setAllowRemove(true);
        modelPage.setAllowClear(true);
        modelPage.setAllowDelete(false);
        modelPage.setAllowSearch(true);
        modelPage.setAllowHubSearch(false);
        modelPage.setAllowGotoEdit(true);
        modelPage.setViewOnly(getViewOnly());
        // call LinkInfo.pageModelCallback(PageModel) to be able to customize this model
        OAObjectCallbackDelegate.onObjectCallbackModel(LinkInfo.class, LinkInfo.P_Page, modelPage);
    
        return modelPage;
    }
    
    public PageSearchModel getPageSearchModel() {
        if (modelPageSearch != null) return modelPageSearch;
        modelPageSearch = new PageSearchModel();
        HubSelectDelegate.adoptWhereHub(modelPageSearch.getHub(), LinkInfo.P_Page, getHub());
        return modelPageSearch;
    }
    
    public HubCopy<LinkInfo> createHubCopy() {
        Hub<LinkInfo> hubLinkInfox = new Hub<>(LinkInfo.class);
        HubCopy<LinkInfo> hc = new HubCopy<>(getHub(), hubLinkInfox, true);
        return hc;
    }
    public LinkInfoModel createCopy() {
        LinkInfoModel mod = new LinkInfoModel(createHubCopy().getHub());
        return mod;
    }
}

